import { mkdir, readFile, rm } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { promisify } from "node:util";
import { execFile } from "node:child_process";
import { describe, expect, it } from "vitest";

import packageJson from "@/package.json";
import { exportSupabaseSeedSql } from "@/scripts/export-supabase-seed";

const execFileAsync = promisify(execFile);

describe("export supabase seed script", () => {
  it("is exposed as a package script for repeatable local import artifact generation", () => {
    expect(packageJson.scripts["export:supabase-seed"]).toBe(
      "vite-node --config vitest.config.ts scripts/export-supabase-seed-cli.ts",
    );
  });

  it("writes a deterministic SQL artifact from the checked-in atlas seed", async () => {
    const tempDir = join(tmpdir(), `atlas-seed-export-${Date.now()}`);
    await mkdir(tempDir, { recursive: true });

    try {
      const outFile = join(tempDir, "seed.sql");
      const result = await exportSupabaseSeedSql({ outFile });
      const sql = await readFile(outFile, "utf8");

      expect(result.filePath).toBe(outFile);
      expect(result.bytes).toBe(Buffer.byteLength(sql, "utf8"));
      expect(sql).toContain("-- Generated by npm run export:supabase-seed.");
      expect(sql).toContain("-- Source: content/seed/vertical-slice.ts");
      expect(sql).toContain("begin;");
      expect(sql).toContain("insert into public.companies");
      expect(sql).toContain("insert into public.subnode_company_coverages");
      expect(sql).toContain("insert into public.supply_relations");
      expect(sql.trim()).toMatch(/commit;$/);
      expect(sql).not.toContain("undefined");
    } finally {
      await rm(tempDir, { recursive: true, force: true });
    }
  });

  it("generates the SQL artifact through the package command", async () => {
    const tempDir = join(tmpdir(), `atlas-seed-command-${Date.now()}`);
    await mkdir(tempDir, { recursive: true });

    try {
      const outFile = join(tempDir, "seed.sql");
      const { stdout } = await execFileAsync(
        "npm",
        ["run", "export:supabase-seed", "--", "--out", outFile],
        { cwd: process.cwd() },
      );
      const sql = await readFile(outFile, "utf8");

      expect(stdout).toContain("Supabase seed SQL exported:");
      expect(sql).toContain("insert into public.companies");
      expect(sql.trim()).toMatch(/commit;$/);
    } finally {
      await rm(tempDir, { recursive: true, force: true });
    }
  });
});
