import type {
  AtlasCompany,
  AtlasSource,
  SubnodeCompanyCoverage,
} from "@/lib/atlas/schema";
import type { AtlasStageId } from "@/lib/atlas/stage-map";

const checkedAt = "2026-07-04T00:00:00.000Z";

type CompanySeed = readonly [
  id: string,
  name: string,
  ticker: string,
  exchange: string,
  market: AtlasCompany["market"],
  currency: string,
  url: string,
];

const companySeeds: readonly CompanySeed[] = [
  ["shanghai-silicon", "沪硅产业", "688126.SH", "SSE STAR", "CN", "CNY", "https://www.sh-nsig.com/"],
  ["tcl-zhonghuan", "TCL 中环", "002129.SZ", "SZSE", "CN", "CNY", "https://www.tclzhonghuan.com/"],
  ["leon-micro", "立昂微", "605358.SH", "SSE", "CN", "CNY", "https://www.leonmicro.com/"],
  ["sanan-opto", "三安光电", "600703.SH", "SSE", "CN", "CNY", "https://www.sanan-e.com/"],
  ["yunnan-germanium", "云南锗业", "002428.SZ", "SZSE", "CN", "CNY", "https://www.yunnan-germanium.com/"],
  ["tongcheng-new-materials", "彤程新材", "603650.SH", "SSE", "CN", "CNY", "https://www.rachem.com/"],
  ["jingrui-electronic-materials", "晶瑞电材", "300655.SZ", "SZSE", "CN", "CNY", "https://www.jingrui-chem.com.cn/"],
  ["nata-opto", "南大光电", "300346.SZ", "SZSE", "CN", "CNY", "https://www.natachem.com/"],
  ["tokyo-ohka", "东京应化", "4186.T", "TSE", "JP", "JPY", "https://www.tok.co.jp/eng/"],
  ["jianghua-micro", "江化微", "603078.SH", "SSE", "CN", "CNY", "https://www.jianghuamem.com/"],
  ["greenda", "格林达", "603931.SH", "SSE", "CN", "CNY", "https://www.greenda.cn/"],
  ["anji-microelectronics", "安集科技", "688019.SH", "SSE STAR", "CN", "CNY", "https://www.anjimicro.com/"],
  ["qingyi-photomask", "清溢光电", "688138.SH", "SSE STAR", "CN", "CNY", "https://www.supermask.com/"],
  ["luwei-optics", "路维光电", "688401.SH", "SSE STAR", "CN", "CNY", "https://www.luwei.com.cn/"],
  ["photronics", "Photronics", "PLAB", "NASDAQ", "US", "USD", "https://www.photronics.com/"],
  ["huate-gas", "华特气体", "688268.SH", "SSE STAR", "CN", "CNY", "https://www.huategas.com/"],
  ["jinhong-gas", "金宏气体", "688106.SH", "SSE STAR", "CN", "CNY", "https://www.jinhonggroup.com/"],
  ["cssc-special-gas", "中船特气", "688146.SH", "SSE STAR", "CN", "CNY", "https://www.csicpride.com/"],
  ["air-liquide", "液化空气", "AI.PA", "EURONEXT PARIS", "EU", "EUR", "https://www.airliquide.com/"],
  ["linde", "林德", "LIN", "NASDAQ", "US", "USD", "https://www.linde.com/"],
  ["yak-technology", "雅克科技", "002409.SZ", "SZSE", "CN", "CNY", "https://www.yokechem.com/"],
  ["entegris", "Entegris", "ENTG", "NASDAQ", "US", "USD", "https://www.entegris.com/"],
  ["merck-kgaa", "默克 KGaA", "MRK.DE", "XETRA", "EU", "EUR", "https://www.merckgroup.com/"],
  ["konfoong-materials", "江丰电子", "300666.SZ", "SZSE", "CN", "CNY", "https://www.kfmic.com/"],
  ["gritek", "有研新材", "600206.SH", "SSE", "CN", "CNY", "https://www.gritek.com/"],
  ["ashitron", "阿石创", "300706.SZ", "SZSE", "CN", "CNY", "https://www.acm-material.com/"],
  ["dinglong", "鼎龙股份", "300054.SZ", "SZSE", "CN", "CNY", "https://www.dl-kg.com/"],
  ["dupont", "杜邦", "DD", "NYSE", "US", "USD", "https://www.dupont.com/"],
  ["fujimi", "Fujimi", "5384.T", "TSE", "JP", "JPY", "https://www.fujimiinc.co.jp/english/"],
  ["ajinomoto", "味之素", "2802.T", "TSE", "JP", "JPY", "https://www.ajinomoto.com/"],
  ["nan-ya-plastics", "南亚塑胶", "1303.TW", "TWSE", "TW", "TWD", "https://www.npc.com.tw/"],
  ["huazheng-new-material", "华正新材", "603186.SH", "SSE", "CN", "CNY", "https://www.wazam.com.cn/"],
  ["huahai-chengke", "华海诚科", "688535.SH", "SSE STAR", "CN", "CNY", "https://www.hhck-em.com/"],
  ["resonac", "Resonac", "4004.T", "TSE", "JP", "JPY", "https://www.resonac.com/"],
  ["sumitomo-bakelite", "住友电木", "4203.T", "TSE", "JP", "JPY", "https://www.sumibe.co.jp/english/"],
  ["vital-new-material", "唯特偶", "301319.SZ", "SZSE", "CN", "CNY", "https://www.szxyt.com/"],
  ["senju-metal", "千住金属", "PRIVATE", "PRIVATE", "PRIVATE", "JPY", "https://www.senju-m.co.jp/en/"],
  ["frd", "飞荣达", "300602.SZ", "SZSE", "CN", "CNY", "https://www.frd.cn/"],
  ["jones-tech", "中石科技", "300684.SZ", "SZSE", "CN", "CNY", "https://www.jones-corp.com/"],
  ["henkel", "汉高", "PRIVATE", "PRIVATE", "PRIVATE", "EUR", "https://www.henkel.com/"],
  ["nord", "诺德股份", "600110.SH", "SSE", "CN", "CNY", "https://www.ndgf.net/"],
  ["jiayuan-technology", "嘉元科技", "688388.SH", "SSE STAR", "CN", "CNY", "https://www.gdjykj.net/"],
  ["defu-technology", "德福科技", "301511.SZ", "SZSE", "CN", "CNY", "https://www.jxdefu.com/"],
  ["copper-crown", "铜冠铜箔", "301217.SZ", "SZSE", "CN", "CNY", "https://www.ahtgcf.com/"],
  ["honghe-technology", "宏和科技", "603256.SH", "SSE", "CN", "CNY", "https://www.gracefabric.com/"],
  ["china-jushi", "中国巨石", "600176.SH", "SSE", "CN", "CNY", "https://www.jushi.com/"],
  ["sinoma-science", "中材科技", "002080.SZ", "SZSE", "CN", "CNY", "https://www.sinomatech.com/"],
  ["cpic", "国际复材", "301526.SZ", "SZSE", "CN", "CNY", "https://www.cpicfiber.com/"],
  ["nittobo", "日东纺", "3110.T", "TSE", "JP", "JPY", "https://www.nittobo.co.jp/eng/"],
  ["dongcai-technology", "东材科技", "601208.SH", "SSE", "CN", "CNY", "https://www.emtco.cn/"],
  ["shengquan-group", "圣泉集团", "605589.SH", "SSE", "CN", "CNY", "https://www.shengquan.com/"],
  ["hongchang-electronic", "宏昌电子", "603002.SH", "SSE", "CN", "CNY", "https://www.graceepoxy.com/"],
  ["meilian-new-materials", "美联新材", "300586.SZ", "SZSE", "CN", "CNY", "https://www.malion.cn/"],
  ["hengtong-optic-electric", "亨通光电", "600487.SH", "SSE", "CN", "CNY", "https://www.htgd.com.cn/"],
  ["ztt", "中天科技", "600522.SH", "SSE", "CN", "CNY", "https://www.chinaztt.com/"],
  ["three-circle", "三环集团", "300408.SZ", "SZSE", "CN", "CNY", "https://www.cctc.cc/"],
  ["tfc-communication", "太辰光", "300570.SZ", "SZSE", "CN", "CNY", "https://www.sz-tfc.com/"],
  ["tianfu-communication", "天孚通信", "300394.SZ", "SZSE", "CN", "CNY", "https://www.tfcsz.com/"],
  ["us-conec", "US Conec", "PRIVATE", "PRIVATE", "PRIVATE", "USD", "https://www.usconec.com/"],
  ["senko", "Senko Advanced Components", "PRIVATE", "PRIVATE", "PRIVATE", "USD", "https://www.senko.com/"],
  ["casttech", "福晶科技", "002222.SZ", "SZSE", "CN", "CNY", "https://www.castech.com/"],
  ["yongxin-optics", "永新光学", "603297.SH", "SSE", "CN", "CNY", "https://www.yxopt.com/"],
  ["tengjing-technology", "腾景科技", "688195.SH", "SSE STAR", "CN", "CNY", "https://www.optowide.com/"],
  ["sunny-optical", "舜宇光学科技", "2382.HK", "HKEX", "HK", "HKD", "https://www.sunnyoptical.com/"],
  ["huitian-adhesive", "回天新材", "300041.SZ", "SZSE", "CN", "CNY", "https://www.huitian.net.cn/"],
  ["kangda-new-materials", "康达新材", "002669.SZ", "SZSE", "CN", "CNY", "https://www.kangda.com/"],
  ["goaland", "高澜股份", "300499.SZ", "SZSE", "CN", "CNY", "https://www.goaland.com.cn/"],
  ["shenling-environment", "申菱环境", "301018.SZ", "SZSE", "CN", "CNY", "https://www.shenling.com/"],
  ["naura", "北方华创", "002371.SZ", "SZSE", "CN", "CNY", "https://www.naura.com/"],
  ["amec", "中微公司", "688012.SH", "SSE STAR", "CN", "CNY", "https://www.amec-inc.com/"],
  ["piotech", "拓荆科技", "688072.SH", "SSE STAR", "CN", "CNY", "https://www.piotech.cn/"],
  ["acm-shanghai", "盛美上海", "688082.SH", "SSE STAR", "CN", "CNY", "https://www.acmrcsh.com/"],
  ["hwatsing", "华海清科", "688120.SH", "SSE STAR", "CN", "CNY", "https://www.hwatsing.com/"],
  ["kingsemi", "芯源微", "688037.SH", "SSE STAR", "CN", "CNY", "https://www.kingsemi.com/"],
  ["smee", "上海微电子", "PRIVATE", "PRIVATE", "PRIVATE", "CNY", "https://www.smee.com.cn/"],
  ["asml", "ASML", "ASML", "NASDAQ", "US", "USD", "https://www.asml.com/"],
  ["nikon", "尼康", "7731.T", "TSE", "JP", "JPY", "https://www.nikon.com/"],
  ["canon", "佳能", "7751.T", "TSE", "JP", "JPY", "https://global.canon/"],
  ["lam-research", "泛林集团", "LRCX", "NASDAQ", "US", "USD", "https://www.lamresearch.com/"],
  ["applied-materials", "应用材料", "AMAT", "NASDAQ", "US", "USD", "https://www.appliedmaterials.com/"],
  ["tokyo-electron", "东京电子", "8035.T", "TSE", "JP", "JPY", "https://www.tel.com/"],
  ["kla", "KLA", "KLAC", "NASDAQ", "US", "USD", "https://www.kla.com/"],
  ["onto-innovation", "Onto Innovation", "ONTO", "NYSE", "US", "USD", "https://ontoinnovation.com/"],
  ["axcelis", "Axcelis", "ACLS", "NASDAQ", "US", "USD", "https://www.axcelis.com/"],
  ["wanye-enterprise", "万业企业", "600641.SH", "SSE", "CN", "CNY", "https://www.600641.com/"],
  ["disco", "DISCO", "6146.T", "TSE", "JP", "JPY", "https://www.disco.co.jp/eg/"],
  ["hans-laser", "大族激光", "002008.SZ", "SZSE", "CN", "CNY", "https://www.hanslaser.com/"],
  ["asmpt", "ASMPT", "0522.HK", "HKEX", "HK", "HKD", "https://www.asmpt.com/"],
  ["besi", "Besi", "BESI.AS", "EURONEXT AMSTERDAM", "EU", "EUR", "https://www.besi.com/"],
  ["kulicke-soffa", "Kulicke & Soffa", "KLIC", "NASDAQ", "US", "USD", "https://www.kns.com/"],
  ["suss-microtec", "SUSS MicroTec", "SMHN.DE", "XETRA", "EU", "EUR", "https://www.suss.com/"],
  ["towa", "TOWA", "6315.T", "TSE", "JP", "JPY", "https://www.towajapan.co.jp/"],
  ["nordson", "Nordson", "NDSN", "NASDAQ", "US", "USD", "https://www.nordson.com/"],
  ["camtek", "Camtek", "CAMT", "NASDAQ", "US", "USD", "https://www.camtek.com/"],
  ["advantest", "爱德万测试", "6857.T", "TSE", "JP", "JPY", "https://www.advantest.com/"],
  ["teradyne", "泰瑞达", "TER", "NASDAQ", "US", "USD", "https://www.teradyne.com/"],
  ["aehr", "Aehr Test Systems", "AEHR", "NASDAQ", "US", "USD", "https://www.aehr.com/"],
  ["changchuan-technology", "长川科技", "300604.SZ", "SZSE", "CN", "CNY", "https://www.hzcctech.com/"],
  ["accotest", "华峰测控", "688200.SH", "SSE STAR", "CN", "CNY", "https://www.accotest.com/"],
  ["formfactor", "FormFactor", "FORM", "NASDAQ", "US", "USD", "https://www.formfactor.com/"],
  ["hans-cnc", "大族数控", "301200.SZ", "SZSE", "CN", "CNY", "https://www.hanscnc.com/"],
  ["dongwei-technology", "东威科技", "688700.SH", "SSE STAR", "CN", "CNY", "https://www.dongweikeji.com/"],
  ["xinqi-micro", "芯碁微装", "688630.SH", "SSE STAR", "CN", "CNY", "https://www.cfmee.cn/"],
  ["juzheng-technology", "矩子科技", "300802.SZ", "SZSE", "CN", "CNY", "https://www.jutze.com.cn/"],
  ["zhengye-technology", "正业科技", "300410.SZ", "SZSE", "CN", "CNY", "https://www.zhengyee.com/"],
  ["mks-instruments", "MKS Instruments", "MKSI", "NASDAQ", "US", "USD", "https://www.mks.com/"],
  ["robotphoenix", "罗博特科", "300757.SZ", "SZSE", "CN", "CNY", "https://www.robotphoenix.com/"],
  ["colibri-technologies", "科瑞技术", "002957.SZ", "SZSE", "CN", "CNY", "https://www.colibri.com.cn/"],
  ["bojay", "博杰股份", "002975.SZ", "SZSE", "CN", "CNY", "https://www.bojay.com/"],
  ["delong-laser", "德龙激光", "688170.SH", "SSE STAR", "CN", "CNY", "https://www.delphilaser.com/"],
  ["keysight", "是德科技", "KEYS", "NYSE", "US", "USD", "https://www.keysight.com/"],
  ["chroma-ate", "致茂电子", "2360.TW", "TWSE", "TW", "TWD", "https://www.chromaate.com/"],
  ["synopsys", "新思科技", "SNPS", "NASDAQ", "US", "USD", "https://www.synopsys.com/"],
  ["cadence", "Cadence", "CDNS", "NASDAQ", "US", "USD", "https://www.cadence.com/"],
  ["siemens", "西门子", "SIE.DE", "XETRA", "EU", "EUR", "https://www.sw.siemens.com/"],
  ["huada-nine", "华大九天", "301269.SZ", "SZSE", "CN", "CNY", "https://www.empyrean-tech.com/"],
  ["primarius", "概伦电子", "688206.SH", "SSE STAR", "CN", "CNY", "https://www.primarius-tech.com/"],
  ["amd", "AMD", "AMD", "NASDAQ", "US", "USD", "https://www.amd.com/"],
  ["intel", "英特尔", "INTC", "NASDAQ", "US", "USD", "https://www.intel.com/"],
  ["arm", "Arm", "ARM", "NASDAQ", "US", "USD", "https://www.arm.com/"],
  ["cambricon", "寒武纪", "688256.SH", "SSE STAR", "CN", "CNY", "https://www.cambricon.com/"],
  ["hygon", "海光信息", "688041.SH", "SSE STAR", "CN", "CNY", "https://www.hygon.cn/"],
  ["loongson", "龙芯中科", "688047.SH", "SSE STAR", "CN", "CNY", "https://www.loongson.cn/"],
  ["huawei", "华为", "PRIVATE", "PRIVATE", "PRIVATE", "CNY", "https://www.huawei.com/"],
  ["horizon-robotics", "地平线机器人", "9660.HK", "HKEX", "HK", "HKD", "https://www.horizon.cc/"],
  ["alchip", "世芯-KY", "3661.TW", "TWSE", "TW", "TWD", "https://www.alchip.com/"],
  ["guc", "创意电子", "3443.TW", "TWSE", "TW", "TWD", "https://www.guc-asic.com/"],
  ["mediatek", "联发科", "2454.TW", "TWSE", "TW", "TWD", "https://www.mediatek.com/"],
  ["smic", "中芯国际", "688981.SH", "SSE STAR", "CN", "CNY", "https://www.smics.com/"],
  ["umc", "联电", "UMC", "NYSE", "US", "USD", "https://www.umc.com/"],
  ["globalfoundries", "GlobalFoundries", "GFS", "NASDAQ", "US", "USD", "https://gf.com/"],
  ["jcet", "长电科技", "600584.SH", "SSE", "CN", "CNY", "https://www.jcetglobal.com/"],
  ["tongfu-microelectronics", "通富微电", "002156.SZ", "SZSE", "CN", "CNY", "https://www.tfme.com/"],
  ["huatian-technology", "华天科技", "002185.SZ", "SZSE", "CN", "CNY", "https://www.ht-tech.com/"],
  ["ase", "日月光投控", "3711.TW", "TWSE", "TW", "TWD", "https://www.aseglobal.com/"],
  ["amkor", "Amkor", "AMKR", "NASDAQ", "US", "USD", "https://amkor.com/"],
  ["rambus", "Rambus", "RMBS", "NASDAQ", "US", "USD", "https://www.rambus.com/"],
  ["montage-technology", "澜起科技", "688008.SH", "SSE STAR", "CN", "CNY", "https://www.montage-tech.com/"],
  ["western-digital", "西部数据", "WDC", "NASDAQ", "US", "USD", "https://www.westerndigital.com/"],
  ["gigadevice", "兆易创新", "603986.SH", "SSE", "CN", "CNY", "https://www.gigadevice.com/"],
  ["longsys", "江波龙", "301308.SZ", "SZSE", "CN", "CNY", "https://www.longsys.com/"],
  ["biwin-storage", "佰维存储", "688525.SH", "SSE STAR", "CN", "CNY", "https://www.biwin.com.cn/"],
  ["techwinsemi", "德明利", "001309.SZ", "SZSE", "CN", "CNY", "https://www.techwinsemi.com/"],
  ["netapp", "NetApp", "NTAP", "NASDAQ", "US", "USD", "https://www.netapp.com/"],
  ["dell", "戴尔科技", "DELL", "NYSE", "US", "USD", "https://www.dell.com/"],
  ["lenovo", "联想集团", "0992.HK", "HKEX", "HK", "HKD", "https://www.lenovo.com/"],
  ["inspur-information", "浪潮信息", "000977.SZ", "SZSE", "CN", "CNY", "https://www.inspur.com/"],
  ["ibiden", "Ibiden", "4062.T", "TSE", "JP", "JPY", "https://www.ibiden.com/"],
  ["shinko-electric", "新光电气工业", "6967.T", "TSE", "JP", "JPY", "https://www.shinko.co.jp/english/"],
  ["unimicron", "欣兴电子", "3037.TW", "TWSE", "TW", "TWD", "https://www.unimicron.com/"],
  ["luxshare", "立讯精密", "002475.SZ", "SZSE", "CN", "CNY", "https://www.luxshare-ict.com/"],
  ["zhaolong-interconnect", "兆龙互连", "300913.SZ", "SZSE", "CN", "CNY", "https://www.zhaolong.com.cn/"],
  ["woer", "沃尔核材", "002130.SZ", "SZSE", "CN", "CNY", "https://www.woer.com/"],
  ["dingtong-technology", "鼎通科技", "688668.SH", "SSE STAR", "CN", "CNY", "https://www.dingtong.net.cn/"],
  ["fii", "工业富联", "601138.SH", "SSE", "CN", "CNY", "https://www.fii-foxconn.com/"],
  ["te-connectivity", "TE Connectivity", "TEL", "NYSE", "US", "USD", "https://www.te.com/"],
  ["amphenol", "安费诺", "APH", "NYSE", "US", "USD", "https://www.amphenol.com/"],
  ["delta-electronics", "台达电子", "2308.TW", "TWSE", "TW", "TWD", "https://www.deltaww.com/"],
  ["megmeet", "麦格米特", "002851.SZ", "SZSE", "CN", "CNY", "https://www.megmeet.com/"],
  ["zhongheng-electric", "中恒电气", "002364.SZ", "SZSE", "CN", "CNY", "https://www.hzzh.com/"],
  ["honor-electronic", "欧陆通", "300870.SZ", "SZSE", "CN", "CNY", "https://www.honor-cn.com/"],
  ["vicor", "Vicor", "VICR", "NASDAQ", "US", "USD", "https://www.vicorpower.com/"],
  ["monolithic-power", "Monolithic Power", "MPWR", "NASDAQ", "US", "USD", "https://www.monolithicpower.com/"],
  ["vertiv", "维谛技术", "VRT", "NYSE", "US", "USD", "https://www.vertiv.com/"],
  ["schneider-electric", "施耐德电气", "SU.PA", "EURONEXT PARIS", "EU", "EUR", "https://www.se.com/"],
  ["eaton", "伊顿", "ETN", "NYSE", "US", "USD", "https://www.eaton.com/"],
  ["kehua-data", "科华数据", "002335.SZ", "SZSE", "CN", "CNY", "https://www.kehua.com/"],
  ["supermicro", "超微电脑", "SMCI", "NASDAQ", "US", "USD", "https://www.supermicro.com/"],
  ["quanta", "广达", "2382.TW", "TWSE", "TW", "TWD", "https://www.quantatw.com/"],
  ["wistron", "纬创", "3231.TW", "TWSE", "TW", "TWD", "https://www.wistron.com/"],
  ["huaqin", "华勤技术", "603296.SH", "SSE", "CN", "CNY", "https://www.huaqin.com/"],
  ["jabil", "捷普", "JBL", "NYSE", "US", "USD", "https://www.jabil.com/"],
  ["lingyi-i-tech", "领益智造", "002600.SZ", "SZSE", "CN", "CNY", "https://www.lingyiitech.com/"],
  ["accelink", "光迅科技", "002281.SZ", "SZSE", "CN", "CNY", "https://www.accelink.com/"],
  ["huagong-tech", "华工科技", "000988.SZ", "SZSE", "CN", "CNY", "https://www.hgtech.com.cn/"],
  ["yuanjie-technology", "源杰科技", "688498.SH", "SSE STAR", "CN", "CNY", "https://www.yj-semitech.com/"],
  ["everbright-photonics", "长光华芯", "688048.SH", "SSE STAR", "CN", "CNY", "https://www.everbrightphotonics.com/"],
  ["sijia-photonics", "仕佳光子", "688313.SH", "SSE STAR", "CN", "CNY", "https://www.sjphotons.com/"],
  ["dekolink", "德科立", "688205.SH", "SSE STAR", "CN", "CNY", "https://www.dk-laser.com/"],
  ["o-net", "昂纳科技", "0877.HK", "HKEX", "HK", "HKD", "https://www.o-netcom.com/"],
  ["gigalight", "光库科技", "300620.SZ", "SZSE", "CN", "CNY", "https://www.gigalight.com/"],
  ["credosemi", "Credo", "CRDO", "NASDAQ", "US", "USD", "https://www.credosemi.com/"],
  ["macom", "MACOM", "MTSI", "NASDAQ", "US", "USD", "https://www.macom.com/"],
  ["maxlinear", "MaxLinear", "MXL", "NASDAQ", "US", "USD", "https://www.maxlinear.com/"],
  ["calient", "CALIENT", "PRIVATE", "PRIVATE", "PRIVATE", "USD", "https://www.calient.net/"],
  ["polatis", "Polatis", "PRIVATE", "PRIVATE", "PRIVATE", "USD", "https://www.polatis.com/"],
  ["cisco", "思科", "CSCO", "NASDAQ", "US", "USD", "https://www.cisco.com/"],
  ["unisplendour", "紫光股份", "000938.SZ", "SZSE", "CN", "CNY", "https://www.thunis.com/"],
  ["ruijie-networks", "星网锐捷", "002396.SZ", "SZSE", "CN", "CNY", "https://www.ruijienetworks.com/"],
  ["centec", "盛科通信", "688702.SH", "SSE STAR", "CN", "CNY", "https://www.centec.com/"],
  ["zte", "中兴通讯", "000063.SZ", "SZSE", "CN", "CNY", "https://www.zte.com.cn/"],
  ["wus-printed-circuit", "沪电股份", "002463.SZ", "SZSE", "CN", "CNY", "https://www.wuscn.com/"],
  ["dongshan-precision", "东山精密", "002384.SZ", "SZSE", "CN", "CNY", "https://www.dsbj.com/"],
  ["kinwong", "景旺电子", "603228.SH", "SSE", "CN", "CNY", "https://www.kinwong.com/"],
  ["aoshikang", "奥士康", "002913.SZ", "SZSE", "CN", "CNY", "https://www.askpcb.com/"],
  ["gds", "万国数据", "GDS", "NASDAQ", "US", "USD", "https://www.gds-services.com/"],
  ["vnet", "世纪互联", "VNET", "NASDAQ", "US", "USD", "https://www.vnet.com/"],
  ["range-intelligent", "润泽科技", "300442.SZ", "SZSE", "CN", "CNY", "https://www.rangeidc.com/"],
  ["athub", "奥飞数据", "300738.SZ", "SZSE", "CN", "CNY", "https://www.aofei.com/"],
  ["data-port", "数据港", "603881.SH", "SSE", "CN", "CNY", "https://www.athub.com/"],
  ["sinnet", "光环新网", "300383.SZ", "SZSE", "CN", "CNY", "https://www.sinnet.com.cn/"],
  ["wangsu", "网宿科技", "300017.SZ", "SZSE", "CN", "CNY", "https://www.wangsu.com/"],
  ["sugon", "中科曙光", "603019.SH", "SSE", "CN", "CNY", "https://www.sugon.com/"],
  ["envicool", "英维克", "002837.SZ", "SZSE", "CN", "CNY", "https://www.envicool.com/"],
  ["coxon", "科创新源", "300731.SZ", "SZSE", "CN", "CNY", "https://www.coxon.com.cn/"],
  ["alibaba", "阿里巴巴", "BABA", "NYSE", "US", "USD", "https://www.alibabacloud.com/"],
  ["tencent", "腾讯控股", "0700.HK", "HKEX", "HK", "HKD", "https://www.tencent.com/"],
  ["baidu", "百度", "BIDU", "NASDAQ", "US", "USD", "https://www.baidu.com/"],
  ["amazon", "亚马逊", "AMZN", "NASDAQ", "US", "USD", "https://aws.amazon.com/"],
  ["microsoft", "微软", "MSFT", "NASDAQ", "US", "USD", "https://azure.microsoft.com/"],
  ["alphabet", "Alphabet", "GOOGL", "NASDAQ", "US", "USD", "https://cloud.google.com/"],
  ["meta", "Meta", "META", "NASDAQ", "US", "USD", "https://ai.meta.com/"],
  ["cloudflare", "Cloudflare", "NET", "NYSE", "US", "USD", "https://www.cloudflare.com/"],
  ["salesforce", "Salesforce", "CRM", "NYSE", "US", "USD", "https://www.salesforce.com/"],
  ["servicenow", "ServiceNow", "NOW", "NYSE", "US", "USD", "https://www.servicenow.com/"],
  ["uipath", "UiPath", "PATH", "NYSE", "US", "USD", "https://www.uipath.com/"],
  ["kingsoft-office", "金山办公", "688111.SH", "SSE STAR", "CN", "CNY", "https://www.wps.cn/"],
  ["iflytek", "科大讯飞", "002230.SZ", "SZSE", "CN", "CNY", "https://www.iflytek.com/"],
  ["adobe", "Adobe", "ADBE", "NASDAQ", "US", "USD", "https://www.adobe.com/"],
  ["palantir", "Palantir", "PLTR", "NYSE", "US", "USD", "https://www.palantir.com/"],
  ["openai", "OpenAI", "PRIVATE", "PRIVATE", "PRIVATE", "USD", "https://openai.com/"],
  ["anthropic", "Anthropic", "PRIVATE", "PRIVATE", "PRIVATE", "USD", "https://www.anthropic.com/"],
  ["parallel-tech", "并行科技", "839493.BJ", "BSE", "CN", "CNY", "https://www.pxtech.com/"],
  ["capital-online", "首都在线", "300846.SZ", "SZSE", "CN", "CNY", "https://www.capitalonline.net/"],
  ["ucloud", "优刻得", "688158.SH", "SSE STAR", "CN", "CNY", "https://www.ucloud.cn/"],
  ["litong-electronics", "利通电子", "603629.SH", "SSE", "CN", "CNY", "https://www.wx-liton.com/"],
  ["sharetronic", "协创数据", "300857.SZ", "SZSE", "CN", "CNY", "https://www.sharetronic.com/"],
  ["hongjing-technology", "宏景科技", "301396.SZ", "SZSE", "CN", "CNY", "https://www.hongjingtech.com/"],
];

type ExistingCompanySourceSeed = readonly [id: string, name: string, url: string];

const existingCompanySourceSeeds: readonly ExistingCompanySourceSeed[] = [
  ["broadcom", "博通", "https://www.broadcom.com/"],
  ["marvell", "迈威尔科技", "https://www.marvell.com/"],
  ["coherent", "Coherent", "https://www.coherent.com/"],
  ["lumentum", "Lumentum", "https://www.lumentum.com/"],
  ["corning", "康宁", "https://www.corning.com/"],
  ["tsmc", "台积电", "https://www.tsmc.com/"],
  ["nvidia", "英伟达", "https://www.nvidia.com/"],
  ["sk-hynix", "SK 海力士", "https://www.skhynix.com/"],
  ["micron", "美光科技", "https://www.micron.com/"],
  ["samsung-electronics", "三星电子", "https://www.samsung.com/semiconductor/"],
  ["arista", "Arista Networks", "https://www.arista.com/"],
  ["fabrinet", "Fabrinet", "https://www.fabrinet.com/"],
  ["zhongji-innolight", "中际旭创", "https://www.innolight.com/"],
  ["eoptolink", "新易盛", "https://www.eoptolink.com/"],
  ["shennan-circuits", "深南电路", "https://www.scc.com.cn/"],
  ["victory-giant", "胜宏科技", "https://www.shpcb.com/"],
  ["shengyi-technology", "生益科技", "https://www.syst.com.cn/"],
  ["kingboard-laminates", "建滔积层板", "https://www.kblaminates.com/"],
  ["axt", "AXT", "https://www.axt.com/"],
  ["sumitomo-electric", "住友电工", "https://sumitomoelectric.com/"],
  ["soitec", "Soitec", "https://www.soitec.com/"],
  ["globalwafers", "环球晶圆", "https://www.sas-globalwafers.com/"],
  ["yofc", "长飞光纤光缆", "https://www.yofc.com/"],
  ["rogers", "Rogers", "https://www.rogerscorp.com/"],
];

const allCompanySourceSeeds = [
  ...companySeeds.map(([id, name, , , , , url]) => [id, name, url] as const),
  ...existingCompanySourceSeeds,
] as const;

export const coverageCompanies: AtlasCompany[] = companySeeds.map(
  ([id, name, ticker, exchange, market, currency]) => ({
    id,
    name,
    ticker,
    exchange,
    market,
    currency,
  }),
);

export const coverageSources: AtlasSource[] = allCompanySourceSeeds.map(
  ([id, name, url]) => ({
    id: `company-${id}`,
    title: `${name} 官方资料`,
    url,
    publisher: name,
    checkedAt,
  }),
);

type CoverageSeed = readonly [
  stageId: AtlasStageId,
  groupId: string,
  subnodeId: string,
  role: string,
  companyIds: readonly string[],
];

const coverageSeeds: readonly CoverageSeed[] = [
  ["materials", "wafer-substrate", "silicon-wafer", "硅片材料", ["shanghai-silicon", "tcl-zhonghuan", "leon-micro"]],
  ["materials", "wafer-substrate", "soi", "SOI / 硅光衬底", ["soitec", "globalwafers", "shanghai-silicon"]],
  ["materials", "wafer-substrate", "inp", "InP 化合物半导体衬底", ["axt", "sumitomo-electric", "yunnan-germanium"]],
  ["materials", "wafer-substrate", "gaas", "GaAs 化合物半导体衬底", ["sanan-opto", "axt", "yunnan-germanium"]],
  ["materials", "patterning-materials", "photoresist", "半导体光刻胶", ["tokyo-ohka", "tongcheng-new-materials", "jingrui-electronic-materials", "nata-opto"]],
  ["materials", "patterning-materials", "developer", "显影液 / 配套湿化学品", ["greenda", "jianghua-micro", "jingrui-electronic-materials"]],
  ["materials", "patterning-materials", "stripper", "剥离液 / 清洗配套化学品", ["jianghua-micro", "jingrui-electronic-materials", "anji-microelectronics"]],
  ["materials", "patterning-materials", "photomask", "半导体掩膜版", ["qingyi-photomask", "luwei-optics", "photronics"]],
  ["materials", "thin-film-deposition-materials", "electronic-gases", "电子特气", ["huate-gas", "jinhong-gas", "cssc-special-gas", "air-liquide", "linde"]],
  ["materials", "thin-film-deposition-materials", "precursors", "薄膜沉积前驱体", ["nata-opto", "yak-technology", "entegris", "merck-kgaa"]],
  ["materials", "thin-film-deposition-materials", "targets", "溅射靶材", ["konfoong-materials", "gritek", "ashitron"]],
  ["materials", "cmp-wet-chemicals", "cmp-slurry", "CMP 抛光液", ["anji-microelectronics", "dinglong", "fujimi", "dupont"]],
  ["materials", "cmp-wet-chemicals", "cmp-pad", "CMP 抛光垫", ["dinglong", "dupont", "fujimi"]],
  ["materials", "cmp-wet-chemicals", "wet-electronic-chemicals", "高纯湿电子化学品", ["jianghua-micro", "jingrui-electronic-materials", "greenda"]],
  ["materials", "packaging-materials", "abf", "ABF 载板材料", ["ajinomoto", "nan-ya-plastics", "huazheng-new-material"]],
  ["materials", "packaging-materials", "bt", "BT 载板材料", ["nan-ya-plastics", "shengyi-technology", "kingboard-laminates"]],
  ["materials", "packaging-materials", "underfill", "底填材料", ["henkel", "resonac", "huahai-chengke"]],
  ["materials", "packaging-materials", "emc", "环氧塑封料", ["huahai-chengke", "sumitomo-bakelite", "resonac"]],
  ["materials", "packaging-materials", "solder-balls-paste", "锡球 / 锡膏", ["senju-metal", "vital-new-material", "sumitomo-bakelite"]],
  ["materials", "packaging-materials", "tim", "热界面材料", ["frd", "jones-tech", "henkel"]],
  ["materials", "pcb-materials", "low-loss-ccl", "低损耗高速覆铜板", ["shengyi-technology", "kingboard-laminates", "rogers", "huazheng-new-material"]],
  ["materials", "pcb-materials", "copper-foil", "电子铜箔", ["nord", "jiayuan-technology", "defu-technology", "copper-crown"]],
  ["materials", "pcb-materials", "glass-fabric", "电子级玻纤布", ["honghe-technology", "china-jushi", "sinoma-science", "cpic", "nittobo"]],
  ["materials", "pcb-materials", "resin", "PCB 树脂体系", ["dongcai-technology", "shengquan-group", "hongchang-electronic", "meilian-new-materials"]],
  ["materials", "optical-communication-materials", "optical-fiber-preform", "光纤预制棒", ["yofc", "corning", "hengtong-optic-electric"]],
  ["materials", "optical-communication-materials", "optical-fiber", "光纤光缆", ["yofc", "hengtong-optic-electric", "ztt", "corning"]],
  ["materials", "optical-communication-materials", "ceramic-ferrule", "陶瓷插芯", ["three-circle", "tfc-communication", "senko"]],
  ["materials", "optical-communication-materials", "mt-ferrule", "MT Ferrule / 多芯连接器", ["us-conec", "senko", "tfc-communication"]],
  ["materials", "optical-communication-materials", "lens", "光通信透镜", ["casttech", "tengjing-technology", "yongxin-optics", "sunny-optical"]],
  ["materials", "optical-communication-materials", "optical-adhesive", "光学胶", ["huitian-adhesive", "kangda-new-materials", "henkel"]],
  ["materials", "thermal-management-materials", "coolant", "液冷冷却液", ["envicool", "goaland", "shenling-environment", "frd"]],
  ["materials", "thermal-management-materials", "thermal-pad", "导热垫片", ["frd", "jones-tech", "henkel"]],
  ["materials", "thermal-management-materials", "thermal-gel", "导热凝胶", ["jones-tech", "frd", "henkel"]],
  ["materials", "thermal-management-materials", "phase-change-material", "相变热界面材料", ["jones-tech", "frd", "henkel"]],

  ["equipment", "front-end-equipment", "lithography", "光刻设备", ["asml", "nikon", "canon", "smee"]],
  ["equipment", "front-end-equipment", "etch", "刻蚀设备", ["lam-research", "amec", "naura", "applied-materials"]],
  ["equipment", "front-end-equipment", "deposition", "薄膜沉积设备", ["applied-materials", "naura", "piotech", "tokyo-electron"]],
  ["equipment", "front-end-equipment", "ion-implantation", "离子注入设备", ["axcelis", "applied-materials", "wanye-enterprise", "naura"]],
  ["equipment", "front-end-equipment", "cmp-equipment", "CMP 设备", ["hwatsing", "applied-materials", "tokyo-electron"]],
  ["equipment", "front-end-equipment", "cleaning", "清洗设备", ["acm-shanghai", "naura", "tokyo-electron", "lam-research"]],
  ["equipment", "front-end-equipment", "metrology-inspection", "量测检测设备", ["kla", "onto-innovation", "camtek", "kingsemi"]],
  ["equipment", "packaging-equipment", "dicing", "切割设备", ["disco", "hans-laser", "delong-laser", "asmpt"]],
  ["equipment", "packaging-equipment", "die-attach", "贴片设备", ["asmpt", "besi", "kulicke-soffa"]],
  ["equipment", "packaging-equipment", "bonding", "键合设备", ["asmpt", "besi", "kulicke-soffa"]],
  ["equipment", "packaging-equipment", "hybrid-bonding", "混合键合设备", ["besi", "suss-microtec", "asmpt"]],
  ["equipment", "packaging-equipment", "molding", "塑封设备", ["towa", "asmpt", "kulicke-soffa"]],
  ["equipment", "packaging-equipment", "underfill-equipment", "底填设备", ["nordson", "asmpt", "besi"]],
  ["equipment", "packaging-equipment", "package-inspection", "封装检测设备", ["camtek", "kla", "onto-innovation"]],
  ["equipment", "test-equipment", "prober", "探针台", ["tokyo-electron", "formfactor", "changchuan-technology"]],
  ["equipment", "test-equipment", "tester", "测试机", ["advantest", "teradyne", "changchuan-technology", "accotest"]],
  ["equipment", "test-equipment", "burn-in-equipment", "老化测试设备", ["aehr", "changchuan-technology", "advantest"]],
  ["equipment", "test-equipment", "high-speed-test", "高速芯片 / 器件测试", ["advantest", "teradyne", "keysight"]],
  ["equipment", "pcb-equipment", "drilling", "PCB 钻孔设备", ["hans-cnc", "hans-laser", "mks-instruments"]],
  ["equipment", "pcb-equipment", "plating", "PCB 电镀设备", ["dongwei-technology", "mks-instruments", "hans-cnc"]],
  ["equipment", "pcb-equipment", "lamination", "PCB 压合设备", ["hans-cnc", "zhengye-technology", "mks-instruments"]],
  ["equipment", "pcb-equipment", "exposure", "PCB 直接成像 / 曝光", ["xinqi-micro", "hans-cnc", "kla"]],
  ["equipment", "pcb-equipment", "aoi", "PCB AOI 检测", ["juzheng-technology", "zhengye-technology", "kla"]],
  ["equipment", "optical-module-equipment", "optical-coupling", "光耦合设备", ["robotphoenix", "colibri-technologies", "asmpt", "mks-instruments"]],
  ["equipment", "optical-module-equipment", "precision-assembly", "精密贴装设备", ["asmpt", "robotphoenix", "colibri-technologies", "bojay", "fabrinet"]],
  ["equipment", "optical-module-equipment", "active-alignment", "主动对准设备", ["robotphoenix", "colibri-technologies", "asmpt", "mks-instruments"]],
  ["equipment", "optical-module-equipment", "optical-high-speed-test", "光模块 / CPO 高速测试", ["keysight", "chroma-ate", "teradyne", "bojay"]],
  ["equipment", "optical-module-equipment", "optical-burn-in", "光模块老化测试", ["chroma-ate", "keysight", "fabrinet", "bojay"]],

  ["ai-chip", "design-stack", "eda-ip", "EDA / 半导体 IP", ["synopsys", "cadence", "huada-nine", "primarius"]],
  ["ai-chip", "design-stack", "architecture-design", "AI 芯片架构设计", ["nvidia", "amd", "huawei", "cambricon"]],
  ["ai-chip", "compute-chip-types", "gpu", "GPU / AI 加速器", ["nvidia", "amd", "intel", "hygon"]],
  ["ai-chip", "compute-chip-types", "asic", "AI ASIC / 定制芯片", ["broadcom", "marvell", "alchip", "guc"]],
  ["ai-chip", "compute-chip-types", "npu", "NPU / AI 推理芯片", ["cambricon", "horizon-robotics", "huawei", "mediatek"]],
  ["ai-chip", "compute-chip-types", "cpu", "CPU", ["intel", "amd", "arm", "hygon", "loongson"]],
  ["ai-chip", "compute-chip-types", "switch-asic-node", "交换 ASIC", ["broadcom", "nvidia", "marvell", "centec"]],
  ["ai-chip", "manufacturing-interface", "wafer-fabrication", "晶圆制造", ["tsmc", "smic", "umc", "globalfoundries"]],
  ["ai-chip", "manufacturing-interface", "bare-die", "裸 Die / 晶圆出货", ["nvidia", "amd", "broadcom", "tsmc"]],
  ["ai-chip", "manufacturing-interface", "hbm-interface", "HBM PHY / 控制器接口", ["synopsys", "cadence", "rambus", "montage-technology"]],
  ["ai-chip", "manufacturing-interface", "packaging-interface", "先进封装接口", ["tsmc", "ase", "jcet", "amkor"]],

  ["hbm-memory", "hbm-stack", "dram-die", "HBM DRAM Die", ["sk-hynix", "micron", "samsung-electronics"]],
  ["hbm-memory", "hbm-stack", "tsv", "TSV / 硅通孔工艺", ["sk-hynix", "samsung-electronics", "micron", "tsmc"]],
  ["hbm-memory", "hbm-stack", "wafer-thinning", "HBM 晶圆减薄", ["sk-hynix", "micron", "disco", "samsung-electronics"]],
  ["hbm-memory", "hbm-stack", "stacking-bonding", "HBM 堆叠与键合", ["sk-hynix", "samsung-electronics", "micron", "ase"]],
  ["hbm-memory", "hbm-stack", "hbm-test", "HBM 测试", ["advantest", "teradyne", "sk-hynix", "micron"]],
  ["hbm-memory", "hbm-stack", "hbm-module", "HBM 模组", ["sk-hynix", "micron", "samsung-electronics"]],
  ["hbm-memory", "storage-extension", "ssd", "企业级 SSD", ["samsung-electronics", "micron", "western-digital", "longsys", "biwin-storage", "techwinsemi", "gigadevice"]],
  ["hbm-memory", "storage-extension", "storage-system", "AI 存储系统", ["netapp", "dell", "lenovo", "inspur-information", "sugon"]],

  ["advanced-packaging", "package-inputs", "ai-die", "AI Die 输入", ["nvidia", "amd", "broadcom", "cambricon"]],
  ["advanced-packaging", "package-inputs", "hbm-package-input", "HBM 封装输入", ["sk-hynix", "micron", "samsung-electronics"]],
  ["advanced-packaging", "package-inputs", "underfill-emc-tim", "封装材料输入", ["huahai-chengke", "frd", "jones-tech", "henkel"]],
  ["advanced-packaging", "package-structures", "silicon-interposer", "硅中介层", ["tsmc", "ase", "jcet"]],
  ["advanced-packaging", "package-structures", "cowos", "CoWoS / 2.5D 集成", ["tsmc", "ase", "amkor"]],
  ["advanced-packaging", "package-structures", "two-five-d", "2.5D 封装", ["tsmc", "ase", "jcet", "amkor"]],
  ["advanced-packaging", "package-structures", "three-d-packaging", "3D 封装", ["tsmc", "samsung-electronics", "ase", "jcet"]],
  ["advanced-packaging", "package-structures", "package-substrate", "封装基板", ["ibiden", "shinko-electric", "unimicron", "shennan-circuits"]],
  ["advanced-packaging", "package-structures", "accelerator-module", "AI 加速器模组", ["nvidia", "amd", "fii", "quanta"]],

  ["board-system", "board-interconnect", "high-speed-connector", "高速连接器", ["luxshare", "zhaolong-interconnect", "woer", "dingtong-technology", "amphenol", "te-connectivity"]],
  ["board-system", "board-interconnect", "high-layer-pcb-node", "高速高多层 PCB", ["victory-giant", "wus-printed-circuit", "shennan-circuits", "dongshan-precision", "kinwong", "aoshikang", "fii"]],
  ["board-system", "board-interconnect", "low-loss-ccl-board-node", "低损耗 CCL", ["shengyi-technology", "kingboard-laminates", "rogers"]],
  ["board-system", "power-cooling-structure", "vrm-power-module", "VRM / 电源模块", ["delta-electronics", "megmeet", "honor-electronic", "zhongheng-electric", "vicor", "monolithic-power"]],
  ["board-system", "power-cooling-structure", "liquid-cold-plate", "液冷板 / 散热组件", ["envicool", "goaland", "shenling-environment", "coxon", "frd", "vertiv"]],
  ["board-system", "power-cooling-structure", "accelerator-card", "加速卡 / 板卡", ["nvidia", "amd", "fii", "quanta"]],
  ["board-system", "power-cooling-structure", "motherboard", "服务器主板", ["supermicro", "quanta", "wistron", "inspur-information"]],
  ["board-system", "power-cooling-structure", "mechanical-structure", "整机结构件", ["fii", "luxshare", "lingyi-i-tech", "jabil"]],

  ["optical-interconnect", "optoelectronic-devices", "optical-chip-node", "光芯片", ["accelink", "yuanjie-technology", "sijia-photonics", "everbright-photonics", "coherent", "broadcom"]],
  ["optical-interconnect", "optoelectronic-devices", "laser-node", "高速激光器", ["coherent", "lumentum", "yuanjie-technology", "everbright-photonics", "huagong-tech"]],
  ["optical-interconnect", "optoelectronic-devices", "modulator-node", "高速光调制器", ["coherent", "lumentum", "gigalight", "broadcom"]],
  ["optical-interconnect", "optoelectronic-devices", "tia-driver-node", "TIA / Driver 芯片", ["macom", "credosemi", "maxlinear", "coherent"]],
  ["optical-interconnect", "optoelectronic-devices", "optical-dsp-node", "光模块 DSP", ["marvell", "broadcom", "credosemi"]],
  ["optical-interconnect", "optical-engine-and-connectors", "fa-mpo-node", "FA / MPO / 连接器", ["tianfu-communication", "tfc-communication", "senko", "corning", "us-conec"]],
  ["optical-interconnect", "optical-engine-and-connectors", "optical-engine-node", "光引擎", ["broadcom", "coherent", "tsmc", "fabrinet"]],
  ["optical-interconnect", "optical-products", "cpo-node", "CPO 系统方案", ["broadcom", "nvidia", "tianfu-communication", "zhongji-innolight", "eoptolink", "huagong-tech", "coherent", "marvell"]],
  ["optical-interconnect", "optical-products", "pluggable-optics-node", "可插拔光模块", ["zhongji-innolight", "eoptolink", "accelink", "tianfu-communication", "huagong-tech", "dekolink", "coherent"]],
  ["optical-interconnect", "optical-products", "ocs-node", "OCS 光交换", ["calient", "polatis", "nvidia", "coherent", "tengjing-technology", "casttech", "gigalight", "dekolink"]],
  ["optical-interconnect", "optical-products", "switch-near-package", "交换 ASIC 近端互联", ["broadcom", "tsmc", "nvidia", "amphenol"]],

  ["server-network", "server-systems", "ai-server-node", "AI 服务器", ["fii", "inspur-information", "sugon", "huaqin", "supermicro", "dell"]],
  ["server-network", "server-systems", "accelerator-board", "GPU / 加速器板卡", ["nvidia", "amd", "fii", "quanta"]],
  ["server-network", "server-systems", "nic-dpu", "NIC / DPU", ["nvidia", "broadcom", "marvell", "intel"]],
  ["server-network", "server-systems", "rack", "AI 机柜", ["vertiv", "envicool", "kehua-data", "schneider-electric", "eaton"]],
  ["server-network", "server-systems", "liquid-cooling-system", "液冷系统", ["envicool", "goaland", "shenling-environment", "coxon", "kehua-data", "vertiv"]],
  ["server-network", "network-systems", "ethernet-switch-node", "AI 以太网交换机", ["arista", "cisco", "nvidia", "unisplendour", "ruijie-networks", "zte", "centec"]],
  ["server-network", "network-systems", "optical-link", "高速光链路", ["zhongji-innolight", "eoptolink", "accelink", "tianfu-communication", "huagong-tech", "dekolink", "coherent"]],
  ["server-network", "network-systems", "cluster-network", "AI 集群网络", ["nvidia", "arista", "broadcom", "cisco", "unisplendour", "zte"]],
  ["server-network", "network-systems", "data-center-infrastructure", "数据中心基础设施", ["vertiv", "envicool", "kehua-data", "zhongheng-electric", "range-intelligent", "schneider-electric"]],

  ["compute-applications", "compute-supply", "aidc", "AIDC / 智算中心", ["range-intelligent", "sinnet", "athub", "data-port", "wangsu", "gds", "vnet"]],
  ["compute-applications", "compute-supply", "cloud-provider", "云厂商", ["alibaba", "tencent", "baidu", "amazon", "microsoft", "alphabet"]],
  ["compute-applications", "compute-supply", "compute-rental", "算力租赁", ["parallel-tech", "capital-online", "ucloud", "litong-electronics", "sharetronic", "hongjing-technology", "range-intelligent"]],
  ["compute-applications", "compute-supply", "ai-cluster-node", "AI 集群方案", ["nvidia", "arista", "supermicro", "inspur-information"]],
  ["compute-applications", "platform-model-apps", "training-platform", "训练平台", ["nvidia", "microsoft", "amazon", "alibaba", "baidu"]],
  ["compute-applications", "platform-model-apps", "inference-platform", "推理平台", ["nvidia", "cloudflare", "microsoft", "alibaba", "tencent"]],
  ["compute-applications", "platform-model-apps", "foundation-model", "基础模型", ["openai", "anthropic", "alphabet", "meta", "baidu", "alibaba"]],
  ["compute-applications", "platform-model-apps", "agent-toolchain", "Agent / 工具链", ["microsoft", "salesforce", "servicenow", "uipath", "kingsoft-office", "iflytek"]],
  ["compute-applications", "platform-model-apps", "industry-apps", "行业 AI 应用", ["iflytek", "kingsoft-office", "adobe", "salesforce", "palantir"]],
];

const coverageSourceIds = new Set(coverageSources.map(({ id }) => id));

export const subnodeCompanyCoverages: SubnodeCompanyCoverage[] =
  coverageSeeds.flatMap(([stageId, groupId, subnodeId, role, companyIds]) =>
    companyIds.map((companyId, index) => {
      const sourceId = `company-${companyId}`;
      if (!coverageSourceIds.has(sourceId)) {
        throw new Error(`missing company source for coverage company: ${companyId}`);
      }
      return {
        id: `${stageId}-${groupId}-${subnodeId}-${companyId}`,
        stageId,
        groupId,
        subnodeId,
        companyId,
        rank: index + 1,
        priority: index === 0 ? "leader" : index === 1 ? "important" : "supplementary",
        relevance: "direct",
        evidenceLevel: index <= 1 ? "B" : "C",
        role: `${role}${index === 0 ? "龙头 / 代表公司" : "重要参与者"}`,
        marketShareNote:
          index === 0
            ? "按业务相关性、公开可见度、市占或市值影响力优先排序；待接行情和行业份额数据后动态校正。"
            : "补充覆盖公司，用于后续按市场、估值、客户关系继续筛选。",
        marketCapNote: "当前仅建立公司主数据与节点映射；实时市值、PE、股价后续由行情数据页接入。",
        sourceIds: [sourceId],
      };
    }),
  );
