import type {
  AtlasCompany,
  AtlasIndustryEdge,
  AtlasNode,
  AtlasSnapshot,
  AtlasSource,
  AtlasSupplyRelation,
} from "@/lib/atlas/schema";

const checkedAt = "2026-06-30T12:00:00.000Z";

const companies: AtlasCompany[] = [
  { id: "broadcom", name: "博通", ticker: "AVGO", exchange: "NASDAQ", market: "US", currency: "USD" },
  { id: "marvell", name: "迈威尔科技", ticker: "MRVL", exchange: "NASDAQ", market: "US", currency: "USD" },
  { id: "coherent", name: "Coherent", ticker: "COHR", exchange: "NYSE", market: "US", currency: "USD" },
  { id: "lumentum", name: "Lumentum", ticker: "LITE", exchange: "NASDAQ", market: "US", currency: "USD" },
  { id: "corning", name: "康宁", ticker: "GLW", exchange: "NYSE", market: "US", currency: "USD" },
  { id: "tsmc", name: "台积电", ticker: "TSM", exchange: "NYSE", market: "US", currency: "USD" },
  { id: "nvidia", name: "英伟达", ticker: "NVDA", exchange: "NASDAQ", market: "US", currency: "USD" },
  { id: "sk-hynix", name: "SK 海力士", ticker: "000660.KS", exchange: "KRX", market: "KR", currency: "KRW" },
  { id: "micron", name: "美光科技", ticker: "MU", exchange: "NASDAQ", market: "US", currency: "USD" },
  { id: "samsung-electronics", name: "三星电子", ticker: "005930.KS", exchange: "KRX", market: "KR", currency: "KRW" },
  { id: "arista", name: "Arista Networks", ticker: "ANET", exchange: "NYSE", market: "US", currency: "USD" },
  { id: "fabrinet", name: "Fabrinet", ticker: "FN", exchange: "NYSE", market: "US", currency: "USD" },
  { id: "zhongji-innolight", name: "中际旭创", ticker: "300308.SZ", exchange: "SZSE", market: "CN", currency: "CNY" },
  { id: "eoptolink", name: "新易盛", ticker: "300502.SZ", exchange: "SZSE", market: "CN", currency: "CNY" },
  { id: "shennan-circuits", name: "深南电路", ticker: "002916.SZ", exchange: "SZSE", market: "CN", currency: "CNY" },
  { id: "victory-giant", name: "胜宏科技", ticker: "300476.SZ", exchange: "SZSE", market: "CN", currency: "CNY" },
  { id: "shengyi-technology", name: "生益科技", ticker: "600183.SH", exchange: "SSE", market: "CN", currency: "CNY" },
  { id: "kingboard-laminates", name: "建滔积层板", ticker: "1888.HK", exchange: "HKEX", market: "HK", currency: "HKD" },
  { id: "axt", name: "AXT", ticker: "AXTI", exchange: "NASDAQ", market: "US", currency: "USD" },
  { id: "sumitomo-electric", name: "住友电工", ticker: "5802.T", exchange: "TSE", market: "JP", currency: "JPY" },
  { id: "soitec", name: "Soitec", ticker: "SOI.PA", exchange: "EURONEXT PARIS", market: "EU", currency: "EUR" },
  { id: "globalwafers", name: "环球晶圆", ticker: "6488.TW", exchange: "TWSE", market: "TW", currency: "TWD" },
  { id: "yofc", name: "长飞光纤光缆", ticker: "6869.HK", exchange: "HKEX", market: "HK", currency: "HKD" },
  { id: "rogers", name: "Rogers", ticker: "ROG", exchange: "NYSE", market: "US", currency: "USD" },
];

const sources: AtlasSource[] = [
  {
    id: "axt-inp-2026",
    title: "AXT Announces First Quarter 2026 Financial Results",
    url: "https://investors.axt.com/Investors/news/news-details/2026/AXT-Inc--Announces-First-Quarter-2026-Financial-Results/default.aspx",
    publisher: "AXT",
    publishedAt: "2026-04-30",
    checkedAt,
  },
  {
    id: "sumitomo-compound",
    title: "Compound Semiconductor",
    url: "https://sumitomoelectric.com/products/compound-semiconductor",
    publisher: "Sumitomo Electric",
    checkedAt,
  },
  {
    id: "soitec-photonics-soi",
    title: "Photonics-SOI substrates",
    url: "https://www.soitec.com/home/products/product-platforms/photonics-soi",
    publisher: "Soitec",
    checkedAt,
  },
  {
    id: "globalwafers-soi-ai-2025",
    title: "SOI Trial Production Launched and Silicon Photonics AI Demand",
    url: "https://www.sas-globalwafers.com/en/gwc_news_en_20251209/",
    publisher: "GlobalWafers",
    publishedAt: "2025-12-09",
    checkedAt,
  },
  {
    id: "corning-ovd",
    title: "Manufacturing Excellence in Optical Fibre",
    url: "https://www.corning.com/optical-communications/emea/en/home/products/fiber/manufacturing-excellence.html",
    publisher: "Corning",
    checkedAt,
  },
  {
    id: "yofc-preform-2017",
    title: "YOFC Qianjiang Optical Fibre Preform Base Put into Operation",
    url: "https://en.yofc.com/view/1797.html",
    publisher: "YOFC",
    publishedAt: "2017-03-23",
    checkedAt,
  },
  {
    id: "rogers-low-loss",
    title: "Computing: High-speed, Low-loss Circuit Materials",
    url: "https://rogerscorp.com/applications/computing",
    publisher: "Rogers Corporation",
    checkedAt,
  },
  {
    id: "kingboard-high-speed",
    title: "高速材料产品系列",
    url: "https://www.kblaminates.com/list/199.html",
    publisher: "Kingboard Laminates",
    checkedAt,
  },
  {
    id: "broadcom-bailly-2024",
    title: "Broadcom Delivers 51.2-Tbps Co-Packaged Optics Ethernet Switch Platform",
    url: "https://www.broadcom.com/company/news/product-releases/61946",
    publisher: "Broadcom",
    publishedAt: "2024-03-14",
    checkedAt,
  },
  {
    id: "broadcom-cpo",
    title: "Co-Packaged Optics",
    url: "https://www.broadcom.com/products/fiber-optic-modules-components/co-packaged-optics",
    publisher: "Broadcom",
    checkedAt,
  },
  {
    id: "coherent-cpo-2026",
    title: "Coherent Demonstrates Multiple Technologies for CPO at OFC 2026",
    url: "https://www.coherent.com/news/press-releases/coherent-co-packaged-optics-cpo-technologies-ofc-2026",
    publisher: "Coherent",
    publishedAt: "2026-03-17",
    checkedAt,
  },
  {
    id: "coherent-eml-2022",
    title: "Coherent Introduces 200G InP Electro-Absorption Modulated Lasers",
    url: "https://www.coherent.com/news/press-releases/coherent-introduces-200g-indium-phosphile-electro-absorption-modulated-lasers",
    publisher: "Coherent",
    publishedAt: "2022-09-15",
    checkedAt,
  },
  {
    id: "coherent-optical-portfolio",
    title: "Optical Communications Products for Telecom and Datacom Networks",
    url: "https://www.coherent.com/content/dam/coherent/site/en/resources/brochures/communication-cables/optical-communications-products-for-telecom-and-datacom-networks-br.pdf",
    publisher: "Coherent",
    checkedAt,
  },
  {
    id: "lumentum-cw-lasers",
    title: "CW Lasers for Data Center Optics",
    url: "https://www.lumentum.com/en/products/data-center/cw-lasers",
    publisher: "Lumentum",
    checkedAt,
  },
  {
    id: "marvell-optical-dsp-2024",
    title: "Marvell Announces 5nm Transmit-Only 800G PAM4 Optical DSP",
    url: "https://investor.marvell.com/2024-03-25-Marvell-Announces-Industrys-First-5nm-Transmit-Only-800G-PAM4-Optical-DSP-for-AI-and-Cloud-Interconnects",
    publisher: "Marvell Technology",
    publishedAt: "2024-03-25",
    checkedAt,
  },
  {
    id: "coherent-pluggable-2025",
    title: "Coherent Expands Silicon Photonics Transceivers With 2x400G-FR4 Lite",
    url: "https://www.coherent.com/news/press-releases/uncooled-silicon-photonics-based-2x400g-fr4-lite",
    publisher: "Coherent",
    publishedAt: "2025-03-20",
    checkedAt,
  },
  {
    id: "nvidia-spectrum-x",
    title: "NVIDIA Spectrum-X Ethernet Networking Platform",
    url: "https://www.nvidia.com/en-us/networking/spectrumx/",
    publisher: "NVIDIA",
    checkedAt,
  },
  {
    id: "nvidia-dgx",
    title: "NVIDIA DGX Platform",
    url: "https://www.nvidia.com/en-us/data-center/dgx-platform/",
    publisher: "NVIDIA",
    checkedAt,
  },
  {
    id: "nvidia-sk-hynix-2026",
    title: "NVIDIA and SK hynix Announce Multiyear Technology Partnership",
    url: "https://investor.nvidia.com/news/press-release-details/2026/NVIDIA-and-SK-hynix-Announce-Multiyear-Technology-Partnership-to-Advance-Memory-for-AI-Factories/default.aspx",
    publisher: "NVIDIA",
    publishedAt: "2026-06-07",
    checkedAt,
  },
  {
    id: "shengyi-pcb-capability",
    title: "生益电子技术能力表",
    url: "https://www.sye.com.cn/CompetencyTable/index.aspx",
    publisher: "Shengyi Electronics",
    checkedAt,
  },
  {
    id: "shengyi-ccl-products",
    title: "生益科技高速覆铜板产品",
    url: "https://www.syst.com.cn/cn/product/list_22.aspx?lcid=68",
    publisher: "Shengyi Technology",
    checkedAt,
  },
  {
    id: "shennan-pcb-capability",
    title: "深南电路印制电路板技术能力",
    url: "https://www.scc.com.cn/scc/cpjs/PCB/index.html",
    publisher: "Shennan Circuits",
    checkedAt,
  },
  {
    id: "victory-giant-ai-pcb",
    title: "人工智能与高性能计算 PCB 产品领域",
    url: "https://www.shpcb.com/index.html",
    publisher: "Victory Giant Technology",
    checkedAt,
  },
  {
    id: "innolight-1p6t-2023",
    title: "InnoLight Demonstrates Pluggable 1.6T and Low-power 800G Transceivers",
    url: "https://www.innolight.com/en/news/newsinfo/179.html",
    publisher: "InnoLight",
    publishedAt: "2023-03-03",
    checkedAt,
  },
  {
    id: "eoptolink-800g",
    title: "800G Optical Transceiver Portfolio",
    url: "https://www.eoptolink.com/product-solutions/800g",
    publisher: "Eoptolink",
    checkedAt,
  },
  {
    id: "fabrinet-optical-packaging",
    title: "Fabrinet Advanced Optical Packaging and Manufacturing",
    url: "https://investor.fabrinet.com/",
    publisher: "Fabrinet",
    checkedAt,
  },
  {
    id: "arista-ai-switch-2026",
    title: "Arista Introduces 1.6 Terabit Portfolio for AI Fabrics",
    url: "https://www.arista.com/en/company/news/press-release/24102-pr-20260609",
    publisher: "Arista Networks",
    publishedAt: "2026-06-09",
    checkedAt,
  },
  {
    id: "micron-hbm4-2026",
    title: "Micron in High-volume Production of HBM4",
    url: "https://investors.micron.com/news-releases/news-release-details/micron-high-volume-production-hbm4-designed-nvidia-vera-rubin",
    publisher: "Micron Technology",
    publishedAt: "2026-03-16",
    checkedAt,
  },
  {
    id: "samsung-hbm4-2026",
    title: "Samsung Ships Commercial HBM4 for AI Computing",
    url: "https://news.samsung.com/global/samsung-ships-industry-first-commercial-hbm4-with-ultimate-performance-for-ai-computing",
    publisher: "Samsung Electronics",
    publishedAt: "2026-02-12",
    checkedAt,
  },
  {
    id: "broadcom-tsmc-cpo-2025",
    title: "Broadcom Announces Tomahawk 6 Davisson CPO Switch",
    url: "https://www.broadcom.com/company/news/product-releases/63626",
    publisher: "Broadcom",
    publishedAt: "2025-10-08",
    checkedAt,
  },
];

const node = (
  value: Omit<AtlasNode, "barriers" | "drivers" | "risks"> &
    Partial<Pick<AtlasNode, "barriers" | "drivers" | "risks">>,
): AtlasNode => ({
  barriers: value.barriers ?? ["工艺一致性、客户验证与规模化良率构成进入壁垒"],
  drivers: value.drivers ?? ["AI 集群带宽密度与能效要求持续提升"],
  risks: value.risks ?? ["技术路线迭代、需求波动及扩产节奏错配"],
  ...value,
});

const nodes: AtlasNode[] = [
  node({ id: "inp-material", layer: "materials", kind: "material", name: "磷化铟衬底", englishName: "Indium Phosphide Substrate", summary: "高速光芯片与激光器的关键化合物半导体衬底。", technology: "磷化铟具备直接带隙和高电子迁移率，适合高速激光、探测及调制器件的外延生长。", companyIds: ["axt", "sumitomo-electric"], sourceIds: ["axt-inp-2026", "sumitomo-compound"] }),
  node({ id: "silicon-photonics-material", layer: "materials", kind: "material", name: "硅光子衬底材料", englishName: "Silicon Photonics Substrates", summary: "为硅光波导和光电集成提供低缺陷 SOI 晶圆平台。", technology: "光子级 SOI 需要精确控制顶层硅与埋氧层厚度、均匀性和表面缺陷，以降低波导损耗。", companyIds: ["soitec", "globalwafers"], sourceIds: ["soitec-photonics-soi", "globalwafers-soi-ai-2025"] }),
  node({ id: "optical-fiber-preform", layer: "materials", kind: "material", name: "光纤预制棒", englishName: "Optical Fiber Preform", summary: "通过高纯玻璃预制棒拉制数据中心连接所需光纤。", technology: "OVD 等气相沉积工艺逐层构造高纯石英与折射率剖面，再经烧结和拉丝获得低损耗光纤。", companyIds: ["corning", "yofc"], sourceIds: ["corning-ovd", "yofc-preform-2017"] }),
  node({ id: "low-loss-ccl", layer: "materials", kind: "material", name: "低损耗覆铜板", englishName: "Low-loss Copper Clad Laminate", summary: "承载高速电信号的低介电损耗 PCB 核心基材。", technology: "高速覆铜板通过低损耗树脂、低粗糙度铜箔与稳定玻纤结构控制插损、偏斜和热可靠性。", companyIds: ["shengyi-technology", "kingboard-laminates", "rogers"], sourceIds: ["shengyi-ccl-products", "rogers-low-loss", "kingboard-high-speed"] }),
  node({ id: "optical-chip", layer: "chips", kind: "component", name: "光芯片", englishName: "Photonic Chip", summary: "完成光信号产生、调制、传输或探测的核心芯片。", technology: "光芯片以 InP、硅光等平台集成激光、波导、调制和探测功能，并依赖高精度耦合封装。", companyIds: ["coherent", "lumentum", "broadcom", "tsmc"], sourceIds: ["coherent-cpo-2026", "broadcom-cpo"] }),
  node({ id: "laser", layer: "chips", kind: "component", name: "激光器", englishName: "Laser", summary: "为可插拔光模块或 CPO 光引擎提供连续光源。", technology: "数据中心激光器需在高温与长寿命条件下维持窄线宽、低噪声和高输出功率，CPO 常采用外置光源。", companyIds: ["coherent", "lumentum"], sourceIds: ["lumentum-cw-lasers", "coherent-cpo-2026"] }),
  node({ id: "modulator", layer: "chips", kind: "component", name: "高速光调制器", englishName: "Optical Modulator", summary: "将高速电信号编码到光载波上的关键器件。", technology: "电吸收或硅光调制结构需兼顾带宽、消光比、驱动电压和插入损耗，面向每通道 200G 及更高速度。", companyIds: ["coherent", "lumentum"], sourceIds: ["coherent-eml-2022", "coherent-cpo-2026"] }),
  node({ id: "tia-driver", layer: "chips", kind: "component", name: "TIA 与驱动芯片", englishName: "TIA and Driver IC", summary: "连接模拟光器件与高速数字电路的电芯片。", technology: "驱动器放大调制端电信号，TIA 将微弱光电流转换放大；两者需控制噪声、线性度、功耗与带宽。", companyIds: ["coherent"], sourceIds: ["coherent-optical-portfolio"] }),
  node({ id: "optical-dsp", layer: "chips", kind: "component", name: "光模块 DSP", englishName: "Optical DSP", summary: "补偿高速光链路损伤并完成 PAM4 信号处理。", technology: "光 DSP 负责均衡、时钟恢复、前向纠错接口与 SerDes 适配，先进制程用于降低 800G/1.6T 功耗。", companyIds: ["marvell", "broadcom"], sourceIds: ["marvell-optical-dsp-2024", "broadcom-cpo"] }),
  node({ id: "fa-mpo", layer: "interconnect", kind: "component", name: "光纤阵列与 MPO", englishName: "Fiber Array and MPO", summary: "完成多通道光引擎到外部光纤的高密度连接。", technology: "光纤阵列依靠亚微米级端面与芯片耦合精度，MPO 等多芯连接器还需兼顾低插损、回损和可维护性。", companyIds: ["corning", "coherent"], sourceIds: ["coherent-optical-portfolio", "corning-ovd"] }),
  node({ id: "high-layer-pcb", layer: "interconnect", kind: "component", name: "高多层高速 PCB", englishName: "High-layer-count PCB", summary: "承载交换机与 AI 服务器高速电连接和供电网络。", technology: "高多层板通过背钻、精细线路、低损耗材料和严格层间对准，控制高速信号完整性与大电流供电可靠性。", companyIds: ["shennan-circuits", "victory-giant"], sourceIds: ["shennan-pcb-capability", "victory-giant-ai-pcb"] }),
  node({ id: "switch-asic", layer: "chips", kind: "component", name: "交换 ASIC", englishName: "Switch ASIC", summary: "执行高速以太网转发和拥塞调度的核心逻辑芯片。", technology: "交换 ASIC 集成大容量 SerDes、包缓冲和调度逻辑，先进节点下需要在吞吐、时延、可编程性和功耗间平衡。", companyIds: ["broadcom", "nvidia", "marvell"], sourceIds: ["broadcom-bailly-2024", "nvidia-spectrum-x"] }),
  node({ id: "pluggable-optics", layer: "interconnect", kind: "component", name: "可插拔光模块", englishName: "Pluggable Optics", summary: "安装在交换机面板上的标准化高速光收发模块。", technology: "800G 与 1.6T 可插拔模块集成光芯片、DSP、驱动/TIA 和精密封装，并受面板密度与散热上限制约。", companyIds: ["coherent", "lumentum", "zhongji-innolight", "eoptolink", "fabrinet"], sourceIds: ["coherent-pluggable-2025", "lumentum-cw-lasers", "innolight-1p6t-2023", "eoptolink-800g", "fabrinet-optical-packaging"] }),
  node({ id: "optical-engine", layer: "interconnect", kind: "component", name: "光引擎", englishName: "Optical Engine", summary: "将多通道光电器件封装为靠近交换芯片的功能单元。", technology: "光引擎把硅光或 InP 光子芯片、驱动/TIA 与光纤耦合整合，关键在封装良率、测试覆盖和热管理。", companyIds: ["broadcom", "coherent", "tsmc", "fabrinet"], sourceIds: ["broadcom-bailly-2024", "broadcom-tsmc-cpo-2025", "coherent-cpo-2026", "fabrinet-optical-packaging"] }),
  node({ id: "cpo", layer: "interconnect", kind: "system", name: "共封装光学", englishName: "Co-Packaged Optics", summary: "将光引擎与交换 ASIC 置于同一封装基板附近。", technology: "CPO 缩短高速电走线以降低功耗和损耗，但需解决异质集成、光纤装配、热隔离、可测试性与维修模型。当前仍处商业导入阶段，并非所有场景均已规模量产。", companyIds: ["broadcom", "coherent", "nvidia", "tsmc"], sourceIds: ["broadcom-bailly-2024", "broadcom-tsmc-cpo-2025", "coherent-cpo-2026", "nvidia-spectrum-x"] }),
  node({ id: "hbm", layer: "chips", kind: "component", name: "高带宽内存", englishName: "High Bandwidth Memory", summary: "以 3D 堆叠和宽接口为 AI 加速器提供高带宽内存。", technology: "HBM 通过 TSV 堆叠 DRAM 并与计算芯片在先进封装中互联，核心难点包括堆叠良率、散热、带宽功耗和联合验证。", companyIds: ["sk-hynix", "micron", "samsung-electronics"], sourceIds: ["nvidia-sk-hynix-2026", "micron-hbm4-2026", "samsung-hbm4-2026"] }),
  node({ id: "ethernet-switch", layer: "infrastructure", kind: "system", name: "AI 以太网交换机", englishName: "AI Ethernet Switch", summary: "连接大量 AI 服务器并组织横向扩展网络的设备。", technology: "AI 交换机围绕高吞吐 ASIC、低时延拥塞控制、光电互联和网络操作系统构建，需在大规模集群中维持有效带宽。", companyIds: ["arista", "broadcom", "nvidia"], sourceIds: ["arista-ai-switch-2026", "nvidia-spectrum-x", "broadcom-bailly-2024"] }),
  node({ id: "ai-server", layer: "infrastructure", kind: "system", name: "AI 服务器", englishName: "AI Server", summary: "集成加速器、HBM、网络和电源散热的计算节点。", technology: "AI 服务器需要协同 GPU/加速器、CPU、HBM、NIC、高速互联及液冷供电，并通过系统级设计释放持续算力。", companyIds: ["nvidia"], sourceIds: ["nvidia-dgx", "nvidia-sk-hynix-2026"] }),
  node({ id: "ai-cluster", layer: "infrastructure", kind: "system", name: "AI 计算集群", englishName: "AI Compute Cluster", summary: "以高速网络汇聚大规模服务器的训练与推理系统。", technology: "AI 集群依靠计算、网络、存储和软件栈共同扩展；尾延迟、网络拥塞、故障域与能耗决定有效算力而非仅看芯片峰值。", companyIds: ["nvidia", "arista", "broadcom"], sourceIds: ["nvidia-spectrum-x", "nvidia-dgx"] }),
];

const edge = (from: string, to: string, type: AtlasIndustryEdge["type"] = "supply"): AtlasIndustryEdge => ({
  id: `${from}--${to}`,
  from,
  to,
  type,
});

const industryEdges: AtlasIndustryEdge[] = [
  edge("inp-material", "optical-chip"),
  edge("silicon-photonics-material", "optical-chip"),
  edge("optical-fiber-preform", "fa-mpo"),
  edge("low-loss-ccl", "high-layer-pcb"),
  edge("optical-chip", "laser", "integrate"),
  edge("optical-chip", "modulator", "integrate"),
  edge("laser", "optical-engine"),
  edge("modulator", "optical-engine"),
  edge("tia-driver", "optical-engine"),
  edge("optical-dsp", "pluggable-optics"),
  edge("laser", "pluggable-optics"),
  edge("modulator", "pluggable-optics"),
  edge("fa-mpo", "optical-engine"),
  edge("optical-chip", "optical-engine"),
  edge("optical-engine", "cpo", "integrate"),
  edge("high-layer-pcb", "cpo", "integrate"),
  edge("switch-asic", "cpo", "integrate"),
  edge("cpo", "ethernet-switch", "integrate"),
  edge("pluggable-optics", "ethernet-switch", "integrate"),
  edge("cpo", "ai-server", "deploy"),
  edge("hbm", "ai-server", "integrate"),
  edge("ethernet-switch", "ai-cluster", "deploy"),
  edge("ai-server", "ai-cluster", "deploy"),
];

const supplyRelations: AtlasSupplyRelation[] = [
  {
    id: "sk-hynix--nvidia--next-generation-memory-2026",
    supplierId: "sk-hynix",
    customerId: "nvidia",
    nodeId: "hbm",
    product: "与 NVIDIA AI 基础设施路线协同的下一代先进内存（HBM 节点）及供应扩展",
    status: "company_confirmed",
    evidenceSourceIds: ["nvidia-sk-hynix-2026"],
    announcedAt: "2026-06-07",
  },
];

export const verticalSlice: AtlasSnapshot = {
  nodes,
  companies,
  industryEdges,
  supplyRelations,
  marketSnapshots: [],
  sources,
};
