import type {
  AtlasCompany,
  AtlasIndustryEdge,
  AtlasNode,
  AtlasSnapshot,
  AtlasSource,
  AtlasSupplyRelation,
  CompanyNodeRole,
} from "@/lib/atlas/schema";
import {
  coverageCompanies,
  coverageSources,
  subnodeCompanyCoverages,
} from "@/content/seed/company-coverage";

const checkedAt = "2026-06-30T12:00:00.000Z";

const companies: AtlasCompany[] = [
  { id: "broadcom", name: "博通", ticker: "AVGO", exchange: "NASDAQ", market: "US", currency: "USD" },
  { id: "marvell", name: "迈威尔科技", ticker: "MRVL", exchange: "NASDAQ", market: "US", currency: "USD" },
  { id: "coherent", name: "Coherent", ticker: "COHR", exchange: "NYSE", market: "US", currency: "USD" },
  { id: "lumentum", name: "Lumentum", ticker: "LITE", exchange: "NASDAQ", market: "US", currency: "USD" },
  { id: "corning", name: "康宁", ticker: "GLW", exchange: "NYSE", market: "US", currency: "USD" },
  { id: "tsmc", name: "台积电", ticker: "TSM", exchange: "NYSE", market: "US", currency: "USD" },
  { id: "nvidia", name: "英伟达", ticker: "NVDA", exchange: "NASDAQ", market: "US", currency: "USD" },
  { id: "sk-hynix", name: "SK 海力士", ticker: "000660.KS", exchange: "KRX", market: "KR", currency: "KRW" },
  { id: "micron", name: "美光科技", ticker: "MU", exchange: "NASDAQ", market: "US", currency: "USD" },
  { id: "samsung-electronics", name: "三星电子", ticker: "005930.KS", exchange: "KRX", market: "KR", currency: "KRW" },
  { id: "arista", name: "Arista Networks", ticker: "ANET", exchange: "NYSE", market: "US", currency: "USD" },
  { id: "fabrinet", name: "Fabrinet", ticker: "FN", exchange: "NYSE", market: "US", currency: "USD" },
  { id: "zhongji-innolight", name: "中际旭创", ticker: "300308.SZ", exchange: "SZSE", market: "CN", currency: "CNY" },
  { id: "eoptolink", name: "新易盛", ticker: "300502.SZ", exchange: "SZSE", market: "CN", currency: "CNY" },
  { id: "shennan-circuits", name: "深南电路", ticker: "002916.SZ", exchange: "SZSE", market: "CN", currency: "CNY" },
  { id: "victory-giant", name: "胜宏科技", ticker: "300476.SZ", exchange: "SZSE", market: "CN", currency: "CNY" },
  { id: "shengyi-technology", name: "生益科技", ticker: "600183.SH", exchange: "SSE", market: "CN", currency: "CNY" },
  { id: "kingboard-laminates", name: "建滔积层板", ticker: "1888.HK", exchange: "HKEX", market: "HK", currency: "HKD" },
  { id: "axt", name: "AXT", ticker: "AXTI", exchange: "NASDAQ", market: "US", currency: "USD" },
  { id: "sumitomo-electric", name: "住友电工", ticker: "5802.T", exchange: "TSE", market: "JP", currency: "JPY" },
  { id: "soitec", name: "Soitec", ticker: "SOI.PA", exchange: "EURONEXT PARIS", market: "EU", currency: "EUR" },
  { id: "globalwafers", name: "环球晶圆", ticker: "6488.TW", exchange: "TWSE", market: "TW", currency: "TWD" },
  { id: "yofc", name: "长飞光纤光缆", ticker: "601869.SH", exchange: "SSE", market: "CN", currency: "CNY" },
  { id: "rogers", name: "Rogers", ticker: "ROG", exchange: "NYSE", market: "US", currency: "USD" },
  ...coverageCompanies,
];

const sources: AtlasSource[] = [
  {
    id: "axt-inp-2026",
    title: "AXT Announces First Quarter 2026 Financial Results",
    url: "https://investors.axt.com/Investors/news/news-details/2026/AXT-Inc--Announces-First-Quarter-2026-Financial-Results/default.aspx",
    publisher: "AXT",
    publishedAt: "2026-04-30",
    checkedAt,
  },
  {
    id: "sumitomo-compound",
    title: "Compound Semiconductor",
    url: "https://sumitomoelectric.com/products/compound-semiconductor",
    publisher: "Sumitomo Electric",
    checkedAt,
  },
  {
    id: "soitec-photonics-soi",
    title: "Photonics-SOI substrates",
    url: "https://www.soitec.com/home/products/product-platforms/photonics-soi",
    publisher: "Soitec",
    checkedAt,
  },
  {
    id: "globalwafers-soi-ai-2025",
    title: "SOI Trial Production Launched and Silicon Photonics AI Demand",
    url: "https://www.sas-globalwafers.com/en/gwc_news_en_20251209/",
    publisher: "GlobalWafers",
    publishedAt: "2025-12-09",
    checkedAt,
  },
  {
    id: "corning-ovd",
    title: "Manufacturing Excellence in Optical Fibre",
    url: "https://www.corning.com/optical-communications/emea/en/home/products/fiber/manufacturing-excellence.html",
    publisher: "Corning",
    checkedAt,
  },
  {
    id: "yofc-preform-2017",
    title: "YOFC Qianjiang Optical Fibre Preform Base Put into Operation",
    url: "https://en.yofc.com/view/1797.html",
    publisher: "YOFC",
    publishedAt: "2017-03-23",
    checkedAt,
  },
  {
    id: "rogers-low-loss",
    title: "Computing: High-speed, Low-loss Circuit Materials",
    url: "https://rogerscorp.com/applications/computing",
    publisher: "Rogers Corporation",
    checkedAt,
  },
  {
    id: "kingboard-high-speed",
    title: "高速材料产品系列",
    url: "https://www.kblaminates.com/list/199.html",
    publisher: "Kingboard Laminates",
    checkedAt,
  },
  {
    id: "broadcom-bailly-2024",
    title: "Broadcom Delivers 51.2-Tbps Co-Packaged Optics Ethernet Switch Platform",
    url: "https://www.broadcom.com/company/news/product-releases/61946",
    publisher: "Broadcom",
    publishedAt: "2024-03-14",
    checkedAt,
  },
  {
    id: "broadcom-cpo",
    title: "Co-Packaged Optics",
    url: "https://www.broadcom.com/products/fiber-optic-modules-components/co-packaged-optics",
    publisher: "Broadcom",
    checkedAt,
  },
  {
    id: "coherent-cpo-2026",
    title: "Coherent Demonstrates Multiple Technologies for CPO at OFC 2026",
    url: "https://www.coherent.com/news/press-releases/coherent-co-packaged-optics-cpo-technologies-ofc-2026",
    publisher: "Coherent",
    publishedAt: "2026-03-17",
    checkedAt,
  },
  {
    id: "coherent-eml-2022",
    title: "Coherent Introduces 200G InP Electro-Absorption Modulated Lasers",
    url: "https://www.coherent.com/news/press-releases/coherent-introduces-200g-indium-phosphile-electro-absorption-modulated-lasers",
    publisher: "Coherent",
    publishedAt: "2022-09-15",
    checkedAt,
  },
  {
    id: "coherent-optical-portfolio",
    title: "Optical Communications Products for Telecom and Datacom Networks",
    url: "https://www.coherent.com/content/dam/coherent/site/en/resources/brochures/communication-cables/optical-communications-products-for-telecom-and-datacom-networks-br.pdf",
    publisher: "Coherent",
    checkedAt,
  },
  {
    id: "lumentum-cw-lasers",
    title: "CW Lasers for Data Center Optics",
    url: "https://www.lumentum.com/en/products/data-center/cw-lasers",
    publisher: "Lumentum",
    checkedAt,
  },
  {
    id: "lumentum-eml-200g",
    title: "EML 200G PAM4 CWDM Laser",
    url: "https://www.lumentum.com/en/products/eml-200g-pam4-cwdm-laser",
    publisher: "Lumentum",
    checkedAt,
  },
  {
    id: "lumentum-datacom-transceivers",
    title: "Datacom Transceivers",
    url: "https://www.lumentum.com/en/products/data-center/datacom-transceivers",
    publisher: "Lumentum",
    checkedAt,
  },
  {
    id: "marvell-optical-dsp-2024",
    title: "Marvell Announces Industry’s First 5nm Transmit-Only 800G PAM4 Optical DSP",
    url: "https://www.marvell.com/company/newsroom/marvell-announces-industrys-first-5nm-transmit-only-800g-pam4-optical-dsp-for-ai-and-cloud-interconnects.html",
    publisher: "Marvell Technology",
    publishedAt: "2024-03-25",
    checkedAt,
  },
  {
    id: "coherent-pluggable-2025",
    title: "Coherent Expands Silicon Photonics Transceivers With 2x400G-FR4 Lite",
    url: "https://www.coherent.com/news/press-releases/uncooled-silicon-photonics-based-2x400g-fr4-lite",
    publisher: "Coherent",
    publishedAt: "2025-03-20",
    checkedAt,
  },
  {
    id: "nvidia-spectrum-x",
    title: "NVIDIA Spectrum-X Ethernet Networking Platform",
    url: "https://www.nvidia.com/en-us/networking/spectrumx/",
    publisher: "NVIDIA",
    checkedAt,
  },
  {
    id: "nvidia-dgx",
    title: "NVIDIA DGX Platform",
    url: "https://www.nvidia.com/en-us/data-center/dgx-platform/",
    publisher: "NVIDIA",
    checkedAt,
  },
  {
    id: "nvidia-sk-hynix-2026",
    title: "NVIDIA and SK hynix Announce Multiyear Technology Partnership",
    url: "https://investor.nvidia.com/news/press-release-details/2026/NVIDIA-and-SK-hynix-Announce-Multiyear-Technology-Partnership-to-Advance-Memory-for-AI-Factories/default.aspx",
    publisher: "NVIDIA",
    publishedAt: "2026-06-07",
    checkedAt,
  },
  {
    id: "shengyi-ccl-products",
    title: "Synamic 6GX 低损耗高速覆铜板",
    url: "https://www.syst.com.cn/cn/product/info_16.aspx?itemid=5215",
    publisher: "Shengyi Technology",
    checkedAt,
  },
  {
    id: "shennan-pcb-capability",
    title: "深南电路印制电路板技术能力",
    url: "https://www.scc.com.cn/scc/cpjs/PCB/index.html",
    publisher: "Shennan Circuits",
    checkedAt,
  },
  {
    id: "victory-giant-ai-pcb",
    title: "人工智能与高性能计算 PCB 产品领域",
    url: "https://www.shpcb.com/index.html",
    publisher: "Victory Giant Technology",
    checkedAt,
  },
  {
    id: "innolight-1p6t-2023",
    title: "InnoLight Demonstrates Pluggable 1.6T and Low-power 800G Transceivers",
    url: "https://www.innolight.com/en/news/newsinfo/179.html",
    publisher: "InnoLight",
    publishedAt: "2023-03-03",
    checkedAt,
  },
  {
    id: "eoptolink-800g",
    title: "800G Optical Transceiver Portfolio",
    url: "https://www.eoptolink.com/product-solutions/800g",
    publisher: "Eoptolink",
    checkedAt,
  },
  {
    id: "fabrinet-optical-packaging",
    title: "Fabrinet Fiscal Year 2025 Results and Optical Manufacturing Capabilities",
    url: "https://investor.fabrinet.com/news-releases/news-release-details/fabrinet-announces-fourth-quarter-and-fiscal-year-2025-financial",
    publisher: "Fabrinet",
    publishedAt: "2025-08-18",
    checkedAt,
  },
  {
    id: "arista-ai-switch-2026",
    title: "Arista Introduces 1.6 Terabit Portfolio for AI Fabrics",
    url: "https://www.arista.com/en/company/news/press-release/24102-pr-20260609",
    publisher: "Arista Networks",
    publishedAt: "2026-06-09",
    checkedAt,
  },
  {
    id: "micron-hbm4-2026",
    title: "Micron in High-volume Production of HBM4",
    url: "https://investors.micron.com/news-releases/news-release-details/micron-high-volume-production-hbm4-designed-nvidia-vera-rubin",
    publisher: "Micron Technology",
    publishedAt: "2026-03-16",
    checkedAt,
  },
  {
    id: "samsung-hbm4-2026",
    title: "Samsung Ships Commercial HBM4 for AI Computing",
    url: "https://news.samsung.com/global/samsung-ships-industry-first-commercial-hbm4-with-ultimate-performance-for-ai-computing",
    publisher: "Samsung Electronics",
    publishedAt: "2026-02-12",
    checkedAt,
  },
  {
    id: "broadcom-tsmc-cpo-2025",
    title: "Broadcom Announces Tomahawk 6 Davisson CPO Switch",
    url: "https://www.broadcom.com/company/news/product-releases/63626",
    publisher: "Broadcom",
    publishedAt: "2025-10-08",
    checkedAt,
  },
  {
    id: "marvell-datacenter-switches",
    title: "Data Center Switches: Enabling the AI Cloud",
    url: "https://www.marvell.com/products/switching/datacenter.html",
    publisher: "Marvell Technology",
    checkedAt,
  },
  {
    id: "sk-hynix-nvidia-hbm3e-2026",
    title: "SK hynix Reaffirms Partnership With NVIDIA at GTC 2026",
    url: "https://news.skhynix.com/gtc-2026-exhibition-booth/",
    publisher: "SK hynix",
    publishedAt: "2026-03-16",
    checkedAt,
  },
  {
    id: "sk-hynix-nvidia-supplier-2026",
    title: "SK Group Chairman Attends GTC Taipei 2026 Keynote",
    url: "https://news.skhynix.com/gtc-taipei-2026-keynote/",
    publisher: "SK hynix",
    publishedAt: "2026-06-01",
    checkedAt,
  },
  {
    id: "nvidia-blackwell-platform-2024",
    title: "NVIDIA Blackwell Platform Arrives to Power a New Era of Computing",
    url: "https://nvidianews.nvidia.com/news/nvidia-blackwell-platform-arrives-to-power-a-new-era-of-computing",
    publisher: "NVIDIA",
    publishedAt: "2024-03-18",
    checkedAt,
  },
  {
    id: "vertiv-nvidia-partner-network-2024",
    title: "Vertiv Joins the NVIDIA Partner Network",
    url: "https://www.vertiv.com/en-us/about/news-and-events/corporate-news/vertiv-joins-the-nvidia-partner-network/",
    publisher: "Vertiv",
    publishedAt: "2024-03-18",
    checkedAt,
  },
  ...coverageSources,
];

const nodeRiskProfiles: Record<
  string,
  Pick<AtlasNode, "barriers" | "drivers" | "risks">
> = {
  "inp-material": { barriers: ["大尺寸单晶生长、缺陷密度和外延级表面控制"], drivers: ["高速 EML、CW 激光器与探测器需求"], risks: ["铟资源及出口许可波动"] },
  "silicon-photonics-material": { barriers: ["顶层硅与埋氧层厚度均匀性及超低缺陷"], drivers: ["硅光收发器和 CPO 异质集成扩张"], risks: ["光子平台路线与晶圆尺寸切换"] },
  "optical-fiber-preform": { barriers: ["超高纯沉积、折射率剖面与拉丝一致性"], drivers: ["AI 数据中心多芯高密度布线增长"], risks: ["扩产后普通光纤供需周期反转"] },
  "low-loss-ccl": { barriers: ["低 Df 树脂配方、铜箔界面与批次稳定性"], drivers: ["112G/224G SerDes 推动更低链路插损"], risks: ["材料认证周期长且代际替换加快"] },
  "optical-chip": { barriers: ["光电器件设计、晶圆良率和耦合封装协同"], drivers: ["800G、1.6T 及 CPO 光通道增加"], risks: ["InP、硅光等平台竞争与价格下降"] },
  laser: { barriers: ["高功率、低 RIN、窄线宽与长期可靠性"], drivers: ["硅光模块和外置 CPO 光源需求"], risks: ["热失效、良率及单通道价格下行"] },
  modulator: { barriers: ["高速带宽、消光比、插损与驱动电压平衡"], drivers: ["每通道 200G 向更高速率演进"], risks: ["EML、硅光和薄膜铌酸锂路线分流"] },
  "tia-driver": { barriers: ["模拟前端噪声、线性度、带宽和功耗协同"], drivers: ["高速光通道数及模拟带宽提升"], risks: ["DSP 集成度上升压缩独立芯片空间"] },
  "optical-dsp": { barriers: ["高速 ADC/DAC、均衡算法与先进制程功耗"], drivers: ["800G/1.6T 模块信号完整性要求"], risks: ["LPO/LRO 架构减少部分 DSP 用量"] },
  "fa-mpo": { barriers: ["多芯端面精度、低插损和批量装配一致性"], drivers: ["CPO 光引擎高密度光纤引出需求"], risks: ["连接器标准分化与现场维护难度"] },
  "high-layer-pcb": { barriers: ["高层数对位、背钻、阻抗与大尺寸良率"], drivers: ["AI 服务器和交换机高速端口密度上升"], risks: ["材料成本、资本开支与客户集中度"] },
  "switch-asic": { barriers: ["超大规模 SerDes、缓存调度和先进制程设计"], drivers: ["AI 集群 scale-out 与 scale-up 带宽增长"], risks: ["协议路线、云厂自研和制程成本压力"] },
  "pluggable-optics": { barriers: ["光电封装、散热、固件互通与自动化测试"], drivers: ["800G 放量及 1.6T 端口升级"], risks: ["CPO/LPO 替代与模块价格快速下降"] },
  "optical-engine": { barriers: ["异质封装、光纤耦合、KGD 测试与热隔离"], drivers: ["光电接口向封装近端迁移"], risks: ["早期规格变化和规模制造良率不确定"] },
  cpo: { barriers: ["ASIC 与光引擎共封装、可测试性和维修体系"], drivers: ["51.2T 以上交换系统功耗墙"], risks: ["仍处导入期，量产节奏和客户采用不确定"] },
  hbm: { barriers: ["TSV 堆叠、基底裸片、封装良率与热管理"], drivers: ["大模型训练推理的内存带宽需求"], risks: ["资本开支周期、客户认证和代际爬坡"] },
  "ethernet-switch": { barriers: ["系统散热、网络操作系统和拥塞控制协同"], drivers: ["以太网 AI 后端网络部署扩大"], risks: ["InfiniBand 竞争及云客户采购波动"] },
  "ai-server": { barriers: ["加速器、内存、网络、供电液冷的系统验证"], drivers: ["训练与推理算力基础设施扩张"], risks: ["芯片供应、机柜功率和交付认证约束"] },
  "ai-cluster": { barriers: ["跨万卡调度、故障恢复与端到端性能优化"], drivers: ["模型规模和推理调用量持续增长"], risks: ["利用率不足、能耗成本和架构快速迭代"] },
};

const node = (
  value: Omit<AtlasNode, "barriers" | "drivers" | "risks"> &
    Partial<Pick<AtlasNode, "barriers" | "drivers" | "risks">>,
): AtlasNode => {
  const profile = nodeRiskProfiles[value.id];
  if (!profile) {
    throw new Error(`missing risk profile for node: ${value.id}`);
  }
  return { ...profile, ...value };
};

const nodes: AtlasNode[] = [
  node({ id: "inp-material", layer: "materials", kind: "material", name: "磷化铟衬底", englishName: "Indium Phosphide Substrate", summary: "高速光芯片与激光器的关键化合物半导体衬底。", technology: "磷化铟具备直接带隙和高电子迁移率，适合高速激光、探测及调制器件的外延生长。", companyIds: ["axt", "sumitomo-electric"], sourceIds: ["axt-inp-2026", "sumitomo-compound"] }),
  node({ id: "silicon-photonics-material", layer: "materials", kind: "material", name: "硅光子衬底材料", englishName: "Silicon Photonics Substrates", summary: "为硅光波导和光电集成提供低缺陷 SOI 晶圆平台。", technology: "光子级 SOI 需要精确控制顶层硅与埋氧层厚度、均匀性和表面缺陷，以降低波导损耗。", companyIds: ["soitec", "globalwafers"], sourceIds: ["soitec-photonics-soi", "globalwafers-soi-ai-2025"] }),
  node({ id: "optical-fiber-preform", layer: "materials", kind: "material", name: "光纤预制棒", englishName: "Optical Fiber Preform", summary: "通过高纯玻璃预制棒拉制数据中心连接所需光纤。", technology: "OVD 等气相沉积工艺逐层构造高纯石英与折射率剖面，再经烧结和拉丝获得低损耗光纤。", companyIds: ["corning", "yofc"], sourceIds: ["corning-ovd", "yofc-preform-2017"] }),
  node({ id: "low-loss-ccl", layer: "materials", kind: "material", name: "低损耗覆铜板", englishName: "Low-loss Copper Clad Laminate", summary: "承载高速电信号的低介电损耗 PCB 核心基材。", technology: "高速覆铜板通过低损耗树脂、低粗糙度铜箔与稳定玻纤结构控制插损、偏斜和热可靠性。", companyIds: ["shengyi-technology", "kingboard-laminates", "rogers"], sourceIds: ["shengyi-ccl-products", "rogers-low-loss", "kingboard-high-speed"] }),
  node({ id: "optical-chip", layer: "chips", kind: "component", name: "光芯片", englishName: "Photonic Chip", summary: "完成光信号产生、调制、传输或探测的核心芯片。", technology: "光芯片以 InP、硅光等平台集成激光、波导、调制和探测功能，并依赖高精度耦合封装。", companyIds: ["coherent", "lumentum", "broadcom", "tsmc"], sourceIds: ["coherent-cpo-2026", "broadcom-cpo"] }),
  node({ id: "laser", layer: "chips", kind: "component", name: "激光器", englishName: "Laser", summary: "为可插拔光模块或 CPO 光引擎提供连续光源。", technology: "数据中心激光器需在高温与长寿命条件下维持窄线宽、低噪声和高输出功率，CPO 常采用外置光源。", companyIds: ["coherent", "lumentum"], sourceIds: ["lumentum-cw-lasers", "coherent-cpo-2026"] }),
  node({ id: "modulator", layer: "chips", kind: "component", name: "高速光调制器", englishName: "Optical Modulator", summary: "将高速电信号编码到光载波上的关键器件。", technology: "电吸收或硅光调制结构需兼顾带宽、消光比、驱动电压和插入损耗，面向每通道 200G 及更高速度。", companyIds: ["coherent", "lumentum"], sourceIds: ["coherent-eml-2022", "coherent-cpo-2026"] }),
  node({ id: "tia-driver", layer: "chips", kind: "component", name: "TIA 与驱动芯片", englishName: "TIA and Driver IC", summary: "连接模拟光器件与高速数字电路的电芯片。", technology: "驱动器放大调制端电信号，TIA 将微弱光电流转换放大；两者需控制噪声、线性度、功耗与带宽。", companyIds: ["coherent"], sourceIds: ["coherent-optical-portfolio"] }),
  node({ id: "optical-dsp", layer: "chips", kind: "component", name: "光模块 DSP", englishName: "Optical DSP", summary: "补偿高速光链路损伤并完成 PAM4 信号处理。", technology: "光 DSP 负责均衡、时钟恢复、前向纠错接口与 SerDes 适配，先进制程用于降低 800G/1.6T 功耗。", companyIds: ["marvell", "broadcom"], sourceIds: ["marvell-optical-dsp-2024", "broadcom-cpo"] }),
  node({ id: "fa-mpo", layer: "interconnect", kind: "component", name: "光纤阵列与 MPO", englishName: "Fiber Array and MPO", summary: "完成多通道光引擎到外部光纤的高密度连接。", technology: "光纤阵列依靠亚微米级端面与芯片耦合精度，MPO 等多芯连接器还需兼顾低插损、回损和可维护性。", companyIds: ["corning", "coherent"], sourceIds: ["coherent-optical-portfolio", "corning-ovd"] }),
  node({ id: "high-layer-pcb", layer: "interconnect", kind: "component", name: "高多层高速 PCB", englishName: "High-layer-count PCB", summary: "承载交换机与 AI 服务器高速电连接和供电网络。", technology: "高多层板通过背钻、精细线路、低损耗材料和严格层间对准，控制高速信号完整性与大电流供电可靠性。", companyIds: ["shennan-circuits", "victory-giant"], sourceIds: ["shennan-pcb-capability", "victory-giant-ai-pcb"] }),
  node({ id: "switch-asic", layer: "chips", kind: "component", name: "交换 ASIC", englishName: "Switch ASIC", summary: "执行高速以太网转发和拥塞调度的核心逻辑芯片。", technology: "交换 ASIC 集成大容量 SerDes、包缓冲和调度逻辑，先进节点下需要在吞吐、时延、可编程性和功耗间平衡。", companyIds: ["broadcom", "nvidia", "marvell"], sourceIds: ["broadcom-bailly-2024", "nvidia-spectrum-x"] }),
  node({ id: "pluggable-optics", layer: "interconnect", kind: "component", name: "可插拔光模块", englishName: "Pluggable Optics", summary: "安装在交换机面板上的标准化高速光收发模块。", technology: "800G 与 1.6T 可插拔模块集成光芯片、DSP、驱动/TIA 和精密封装，并受面板密度与散热上限制约。", companyIds: ["coherent", "lumentum", "zhongji-innolight", "eoptolink", "fabrinet"], sourceIds: ["coherent-pluggable-2025", "lumentum-cw-lasers", "innolight-1p6t-2023", "eoptolink-800g", "fabrinet-optical-packaging"] }),
  node({ id: "optical-engine", layer: "interconnect", kind: "component", name: "光引擎", englishName: "Optical Engine", summary: "将多通道光电器件封装为靠近交换芯片的功能单元。", technology: "光引擎把硅光或 InP 光子芯片、驱动/TIA 与光纤耦合整合，关键在封装良率、测试覆盖和热管理。", companyIds: ["broadcom", "coherent", "tsmc", "fabrinet"], sourceIds: ["broadcom-bailly-2024", "broadcom-tsmc-cpo-2025", "coherent-cpo-2026", "fabrinet-optical-packaging"] }),
  node({ id: "cpo", layer: "interconnect", kind: "system", name: "共封装光学", englishName: "Co-Packaged Optics", summary: "将光引擎与交换 ASIC 置于同一封装基板附近。", technology: "CPO 缩短高速电走线以降低功耗和损耗，但需解决异质集成、光纤装配、热隔离、可测试性与维修模型。当前仍处商业导入阶段，并非所有场景均已规模量产。", companyIds: ["broadcom", "coherent", "nvidia", "tsmc"], sourceIds: ["broadcom-bailly-2024", "broadcom-tsmc-cpo-2025", "coherent-cpo-2026", "nvidia-spectrum-x"] }),
  node({ id: "hbm", layer: "chips", kind: "component", name: "高带宽内存", englishName: "High Bandwidth Memory", summary: "以 3D 堆叠和宽接口为 AI 加速器提供高带宽内存。", technology: "HBM 通过 TSV 堆叠 DRAM 并与计算芯片在先进封装中互联，核心难点包括堆叠良率、散热、带宽功耗和联合验证。", companyIds: ["sk-hynix", "micron", "samsung-electronics"], sourceIds: ["nvidia-sk-hynix-2026", "micron-hbm4-2026", "samsung-hbm4-2026"] }),
  node({ id: "ethernet-switch", layer: "infrastructure", kind: "system", name: "AI 以太网交换机", englishName: "AI Ethernet Switch", summary: "连接大量 AI 服务器并组织横向扩展网络的设备。", technology: "AI 交换机围绕高吞吐 ASIC、低时延拥塞控制、光电互联和网络操作系统构建，需在大规模集群中维持有效带宽。", companyIds: ["arista", "broadcom", "nvidia"], sourceIds: ["arista-ai-switch-2026", "nvidia-spectrum-x", "broadcom-bailly-2024"] }),
  node({ id: "ai-server", layer: "infrastructure", kind: "system", name: "AI 服务器", englishName: "AI Server", summary: "集成加速器、HBM、网络和电源散热的计算节点。", technology: "AI 服务器需要协同 GPU/加速器、CPU、HBM、NIC、高速互联及液冷供电，并通过系统级设计释放持续算力。", companyIds: ["nvidia"], sourceIds: ["nvidia-dgx", "nvidia-sk-hynix-2026"] }),
  node({ id: "ai-cluster", layer: "infrastructure", kind: "system", name: "AI 计算集群", englishName: "AI Compute Cluster", summary: "以高速网络汇聚大规模服务器的训练与推理系统。", technology: "AI 集群依靠计算、网络、存储和软件栈共同扩展；尾延迟、网络拥塞、故障域与能耗决定有效算力而非仅看芯片峰值。", companyIds: ["nvidia", "arista", "broadcom"], sourceIds: ["nvidia-spectrum-x", "nvidia-dgx"] }),
];

const role = (
  nodeId: string,
  companyId: string,
  roleName: string,
  product: string,
  sourceIds: string[],
): CompanyNodeRole => ({
  id: `${nodeId}--${companyId}`,
  nodeId,
  companyId,
  role: roleName,
  product,
  sourceIds,
});

const companyNodeRoles: CompanyNodeRole[] = [
  role("inp-material", "axt", "衬底厂商", "磷化铟衬底", ["axt-inp-2026"]),
  role("inp-material", "sumitomo-electric", "衬底厂商", "磷化铟衬底", ["sumitomo-compound"]),
  role("silicon-photonics-material", "soitec", "衬底厂商", "Photonics-SOI 晶圆", ["soitec-photonics-soi"]),
  role("silicon-photonics-material", "globalwafers", "衬底厂商", "硅光用 SOI 晶圆", ["globalwafers-soi-ai-2025"]),
  role("optical-fiber-preform", "corning", "预制棒与光纤厂商", "OVD 预制棒和光纤", ["corning-ovd"]),
  role("optical-fiber-preform", "yofc", "预制棒与光纤厂商", "OVD 光纤预制棒", ["yofc-preform-2017"]),
  role("low-loss-ccl", "shengyi-technology", "高速覆铜板厂商", "Synamic 6GX 低损耗覆铜板", ["shengyi-ccl-products"]),
  role("low-loss-ccl", "kingboard-laminates", "高速覆铜板厂商", "KB 高速低损耗材料", ["kingboard-high-speed"]),
  role("low-loss-ccl", "rogers", "高速覆铜板厂商", "XtremeSpeed 低损耗电路材料", ["rogers-low-loss"]),
  role("optical-chip", "coherent", "光子器件厂商", "InP 与硅光子器件", ["coherent-cpo-2026"]),
  role("optical-chip", "lumentum", "光子器件厂商", "InP EML 光子器件", ["lumentum-eml-200g"]),
  role("optical-chip", "broadcom", "硅光平台厂商", "CPO 硅光光子器件", ["broadcom-cpo"]),
  role("optical-chip", "tsmc", "硅光制造平台", "COUPE 硅光子技术", ["broadcom-tsmc-cpo-2025"]),
  role("laser", "coherent", "激光器厂商", "CPO 外置 InP CW 激光器", ["coherent-cpo-2026"]),
  role("laser", "lumentum", "激光器厂商", "数据中心 CW 激光器", ["lumentum-cw-lasers"]),
  role("modulator", "coherent", "调制器厂商", "200G InP 电吸收调制激光器", ["coherent-eml-2022"]),
  role("modulator", "lumentum", "调制器厂商", "200G PAM4 EML", ["lumentum-eml-200g"]),
  role("tia-driver", "coherent", "模拟光电器件厂商", "驱动器与 TIA", ["coherent-optical-portfolio"]),
  role("optical-dsp", "marvell", "光 DSP 厂商", "Spica Gen2-T 800G PAM4 DSP", ["marvell-optical-dsp-2024"]),
  role("optical-dsp", "broadcom", "光 DSP 平台厂商", "CPO 光电信号处理", ["broadcom-cpo"]),
  role("fa-mpo", "corning", "光纤材料厂商", "光纤阵列所需低损耗光纤", ["corning-ovd"]),
  role("fa-mpo", "coherent", "无源光组件厂商", "光纤阵列与无源光组件", ["coherent-optical-portfolio"]),
  role("high-layer-pcb", "shennan-circuits", "高速 PCB 厂商", "高速高多层板与背板", ["shennan-pcb-capability"]),
  role("high-layer-pcb", "victory-giant", "高速 PCB 厂商", "AI 服务器与交换机高多层 PCB", ["victory-giant-ai-pcb"]),
  role("switch-asic", "broadcom", "交换芯片厂商", "Tomahawk 交换 ASIC", ["broadcom-bailly-2024"]),
  role("switch-asic", "nvidia", "交换芯片厂商", "Spectrum-X 交换芯片平台", ["nvidia-spectrum-x"]),
  role("switch-asic", "marvell", "交换芯片厂商", "Teralynx 数据中心交换芯片", ["marvell-datacenter-switches"]),
  role("pluggable-optics", "coherent", "光模块厂商", "2x400G FR4 Lite 光模块", ["coherent-pluggable-2025"]),
  role("pluggable-optics", "lumentum", "光模块厂商", "800G 与 1.6T OSFP 光模块", ["lumentum-datacom-transceivers"]),
  role("pluggable-optics", "zhongji-innolight", "光模块厂商", "1.6T 与 800G 可插拔光模块", ["innolight-1p6t-2023"]),
  role("pluggable-optics", "eoptolink", "光模块厂商", "800G OSFP 与 QSFP-DD 光模块", ["eoptolink-800g"]),
  role("pluggable-optics", "fabrinet", "光模块制造服务商", "光通信模块精密制造与测试", ["fabrinet-optical-packaging"]),
  role("optical-engine", "broadcom", "光引擎厂商", "Bailly 6.4T 硅光光引擎", ["broadcom-bailly-2024"]),
  role("optical-engine", "coherent", "光引擎厂商", "6.4T socketed CPO 光引擎", ["coherent-cpo-2026"]),
  role("optical-engine", "tsmc", "光子制造平台", "COUPE 光引擎技术", ["broadcom-tsmc-cpo-2025"]),
  role("optical-engine", "fabrinet", "精密光封装服务商", "光通信组件高级光封装", ["fabrinet-optical-packaging"]),
  role("cpo", "broadcom", "CPO 平台厂商", "Bailly 与 Davisson CPO 交换平台", ["broadcom-bailly-2024", "broadcom-tsmc-cpo-2025"]),
  role("cpo", "coherent", "CPO 技术厂商", "socketed CPO 与外置激光方案", ["coherent-cpo-2026"]),
  role("cpo", "nvidia", "CPO 网络平台厂商", "Spectrum-X Ethernet Photonics", ["nvidia-spectrum-x"]),
  role("cpo", "tsmc", "CPO 硅光制造平台", "COUPE 异质光子引擎", ["broadcom-tsmc-cpo-2025"]),
  role("hbm", "sk-hynix", "HBM 厂商", "用于 NVIDIA GB300 的 HBM3E", ["sk-hynix-nvidia-hbm3e-2026"]),
  role("hbm", "micron", "HBM 厂商", "HBM4 36GB 12H", ["micron-hbm4-2026"]),
  role("hbm", "samsung-electronics", "HBM 厂商", "量产 HBM4", ["samsung-hbm4-2026"]),
  role("ethernet-switch", "arista", "交换机系统厂商", "1.6T AI fabric 交换机", ["arista-ai-switch-2026"]),
  role("ethernet-switch", "broadcom", "CPO 交换平台厂商", "Bailly CPO 以太网交换机", ["broadcom-bailly-2024"]),
  role("ethernet-switch", "nvidia", "AI 以太网平台厂商", "Spectrum-X 以太网交换机", ["nvidia-spectrum-x"]),
  role("ai-server", "nvidia", "AI 系统平台厂商", "NVIDIA DGX 系统", ["nvidia-dgx"]),
  role("ai-cluster", "nvidia", "AI 集群平台厂商", "DGX SuperPOD 与 Spectrum-X", ["nvidia-dgx", "nvidia-spectrum-x"]),
  role("ai-cluster", "arista", "AI 网络平台厂商", "AI scale-up 与 scale-out fabric", ["arista-ai-switch-2026"]),
  role("ai-cluster", "broadcom", "AI 网络芯片平台厂商", "面向大规模 AI 集群的 CPO 网络", ["broadcom-bailly-2024"]),
];

const edge = (from: string, to: string, type: AtlasIndustryEdge["type"] = "supply"): AtlasIndustryEdge => ({
  id: `${from}--${to}`,
  from,
  to,
  type,
});

const industryEdges: AtlasIndustryEdge[] = [
  edge("inp-material", "optical-chip"),
  edge("silicon-photonics-material", "optical-chip"),
  edge("optical-fiber-preform", "fa-mpo"),
  edge("low-loss-ccl", "high-layer-pcb"),
  edge("laser", "optical-engine"),
  edge("modulator", "optical-engine"),
  edge("tia-driver", "optical-engine"),
  edge("optical-dsp", "pluggable-optics"),
  edge("laser", "pluggable-optics"),
  edge("modulator", "pluggable-optics"),
  edge("fa-mpo", "optical-engine"),
  edge("optical-chip", "optical-engine"),
  edge("optical-engine", "cpo", "integrate"),
  edge("high-layer-pcb", "cpo", "integrate"),
  edge("switch-asic", "cpo", "integrate"),
  edge("cpo", "ethernet-switch", "integrate"),
  edge("pluggable-optics", "ethernet-switch", "integrate"),
  edge("cpo", "ai-server", "deploy"),
  edge("hbm", "ai-server", "integrate"),
  edge("ethernet-switch", "ai-cluster", "deploy"),
  edge("ai-server", "ai-cluster", "deploy"),
];

const supplyRelations: AtlasSupplyRelation[] = [
  {
    id: "sk-hynix--nvidia--next-generation-memory-2026",
    supplierId: "sk-hynix",
    customerId: "nvidia",
    nodeId: "hbm",
    product: "用于 NVIDIA GB300 系统的 SK hynix HBM3E，并延伸至下一代内存路线协同",
    status: "company_confirmed",
    evidenceSourceIds: ["sk-hynix-nvidia-hbm3e-2026", "sk-hynix-nvidia-supplier-2026", "nvidia-sk-hynix-2026"],
    announcedAt: "2026-03-16",
  },
  {
    id: "micron--nvidia--hbm4-2026",
    supplierId: "micron",
    customerId: "nvidia",
    nodeId: "hbm",
    product: "面向 NVIDIA Vera Rubin 平台的 Micron HBM4 供给与验证路线",
    status: "company_confirmed",
    evidenceSourceIds: ["micron-hbm4-2026"],
    announcedAt: "2026-03-16",
  },
  {
    id: "tsmc--broadcom--cpo-coupe-2025",
    supplierId: "tsmc",
    customerId: "broadcom",
    nodeId: "cpo",
    product: "Broadcom CPO 交换平台中的 TSMC COUPE 光子引擎 / 硅光制造平台",
    status: "company_confirmed",
    evidenceSourceIds: ["broadcom-tsmc-cpo-2025"],
    announcedAt: "2025-10-08",
  },
  {
    id: "tsmc--nvidia--blackwell-4np-hbm-platform-2024",
    supplierId: "tsmc",
    customerId: "nvidia",
    nodeId: "hbm",
    product: "NVIDIA Blackwell 平台使用定制 TSMC 4NP 制程，并与 HBM 及先进封装共同构成 AI 加速平台",
    status: "company_confirmed",
    evidenceSourceIds: ["nvidia-blackwell-platform-2024"],
    announcedAt: "2024-03-18",
  },
  {
    id: "nvidia--amazon--blackwell-cloud-2024",
    supplierId: "nvidia",
    customerId: "amazon",
    nodeId: "ai-cluster",
    product: "AWS 作为首批 Blackwell 云实例伙伴，承载 NVIDIA Grace Blackwell / GB200 AI 云基础设施",
    status: "company_confirmed",
    evidenceSourceIds: ["nvidia-blackwell-platform-2024"],
    announcedAt: "2024-03-18",
  },
  {
    id: "nvidia--alphabet--blackwell-cloud-2024",
    supplierId: "nvidia",
    customerId: "alphabet",
    nodeId: "ai-cluster",
    product: "Google Cloud / Google DeepMind 采用 NVIDIA Blackwell 平台，用于云客户和内部 AI 基础设施",
    status: "company_confirmed",
    evidenceSourceIds: ["nvidia-blackwell-platform-2024"],
    announcedAt: "2024-03-18",
  },
  {
    id: "nvidia--microsoft--blackwell-cloud-2024",
    supplierId: "nvidia",
    customerId: "microsoft",
    nodeId: "ai-cluster",
    product: "Microsoft Azure 将 GB200 Grace Blackwell 处理器引入全球数据中心，面向 AI 工作负载",
    status: "company_confirmed",
    evidenceSourceIds: ["nvidia-blackwell-platform-2024"],
    announcedAt: "2024-03-18",
  },
  {
    id: "nvidia--meta--blackwell-ai-training-2024",
    supplierId: "nvidia",
    customerId: "meta",
    nodeId: "ai-cluster",
    product: "Meta 使用 NVIDIA Blackwell 训练 Llama 模型并建设下一代 Meta AI 基础设施",
    status: "company_confirmed",
    evidenceSourceIds: ["nvidia-blackwell-platform-2024"],
    announcedAt: "2024-03-18",
  },
  {
    id: "nvidia--openai--blackwell-ai-training-2024",
    supplierId: "nvidia",
    customerId: "openai",
    nodeId: "ai-cluster",
    product: "OpenAI 继续与 NVIDIA 合作，使用 Blackwell 算力推进前沿模型训练和推理",
    status: "company_confirmed",
    evidenceSourceIds: ["nvidia-blackwell-platform-2024"],
    announcedAt: "2024-03-18",
  },
  {
    id: "nvidia--dell--blackwell-ai-server-2024",
    supplierId: "nvidia",
    customerId: "dell",
    nodeId: "ai-server",
    product: "Dell 作为 NVIDIA Blackwell 服务器伙伴，交付基于 Blackwell 产品的 AI 服务器",
    status: "company_confirmed",
    evidenceSourceIds: ["nvidia-blackwell-platform-2024"],
    announcedAt: "2024-03-18",
  },
  {
    id: "nvidia--supermicro--blackwell-ai-server-2024",
    supplierId: "nvidia",
    customerId: "supermicro",
    nodeId: "ai-server",
    product: "Supermicro 作为 NVIDIA Blackwell 服务器伙伴，交付基于 Blackwell 产品的 AI 服务器",
    status: "company_confirmed",
    evidenceSourceIds: ["nvidia-blackwell-platform-2024"],
    announcedAt: "2024-03-18",
  },
  {
    id: "nvidia--lenovo--blackwell-ai-server-2024",
    supplierId: "nvidia",
    customerId: "lenovo",
    nodeId: "ai-server",
    product: "Lenovo 作为 NVIDIA Blackwell 服务器伙伴，交付基于 Blackwell 产品的 AI 服务器",
    status: "company_confirmed",
    evidenceSourceIds: ["nvidia-blackwell-platform-2024"],
    announcedAt: "2024-03-18",
  },
  {
    id: "nvidia--fii--blackwell-ai-server-2024",
    supplierId: "nvidia",
    customerId: "fii",
    nodeId: "ai-server",
    product: "NVIDIA 官方 Blackwell 服务器伙伴中的 Foxconn 体系；A股投研映射到工业富联 AI 服务器链",
    status: "multi_source_report",
    evidenceSourceIds: ["nvidia-blackwell-platform-2024", "company-fii"],
    announcedAt: "2024-03-18",
  },
  {
    id: "nvidia--quanta--blackwell-ai-server-2024",
    supplierId: "nvidia",
    customerId: "quanta",
    nodeId: "ai-server",
    product: "QCT / Quanta 作为 NVIDIA Blackwell 服务器伙伴，交付基于 Blackwell 产品的 AI 服务器",
    status: "company_confirmed",
    evidenceSourceIds: ["nvidia-blackwell-platform-2024"],
    announcedAt: "2024-03-18",
  },
  {
    id: "nvidia--cisco--blackwell-ai-server-2024",
    supplierId: "nvidia",
    customerId: "cisco",
    nodeId: "ai-server",
    product: "Cisco 作为 NVIDIA Blackwell 系统伙伴，交付基于 Blackwell 产品的 AI 服务器与网络系统",
    status: "company_confirmed",
    evidenceSourceIds: ["nvidia-blackwell-platform-2024"],
    announcedAt: "2024-03-18",
  },
  {
    id: "vertiv--nvidia--ai-cluster-infrastructure-2024",
    supplierId: "vertiv",
    customerId: "nvidia",
    nodeId: "ai-cluster",
    product: "面向高密度 AI 集群的电源、热管理与数据中心基础设施方案合作",
    status: "company_confirmed",
    evidenceSourceIds: ["vertiv-nvidia-partner-network-2024"],
    announcedAt: "2024-03-18",
  },
  {
    id: "broadcom--arista--merchant-silicon-ai-switch-2026",
    supplierId: "broadcom",
    customerId: "arista",
    nodeId: "ethernet-switch",
    product: "Arista AI 以太网交换机生态中的 Broadcom Tomahawk / Jericho 交换 ASIC 供给线索",
    status: "multi_source_report",
    evidenceSourceIds: ["broadcom-bailly-2024", "arista-ai-switch-2026"],
    announcedAt: "2026-06-09",
  },
];

export const verticalSlice: AtlasSnapshot = {
  nodes,
  companies,
  companyNodeRoles,
  subnodeCompanyCoverages,
  industryEdges,
  supplyRelations,
  marketSnapshots: [],
  sources,
};
