import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

import { verticalSlice } from "@/content/seed/vertical-slice";
import type { AtlasSnapshot } from "@/lib/atlas/schema";
import { buildSupabaseSeedSql } from "@/lib/atlas/supabase-seed-sql";

const defaultOutFile = "supabase/seed.sql";

export interface ExportSupabaseSeedSqlOptions {
  outFile?: string;
  snapshot?: AtlasSnapshot;
}

export interface ExportSupabaseSeedSqlResult {
  filePath: string;
  bytes: number;
}

const buildSeedFileContent = (snapshot: AtlasSnapshot) =>
  [
    "-- Generated by npm run export:supabase-seed.",
    "-- Source: content/seed/vertical-slice.ts",
    "-- Do not edit manually; regenerate after changing checked-in seed data.",
    "",
    buildSupabaseSeedSql(snapshot).trim(),
    "",
  ].join("\n");

export const exportSupabaseSeedSql = async ({
  outFile = defaultOutFile,
  snapshot = verticalSlice,
}: ExportSupabaseSeedSqlOptions = {}): Promise<ExportSupabaseSeedSqlResult> => {
  const filePath = resolve(outFile);
  const content = buildSeedFileContent(snapshot);

  await mkdir(dirname(filePath), { recursive: true });
  await writeFile(filePath, content, "utf8");

  return {
    filePath,
    bytes: Buffer.byteLength(content, "utf8"),
  };
};

export const parseSeedExportOutFile = (args: readonly string[]) => {
  const outEquals = args.find((arg) => arg.startsWith("--out="));
  if (outEquals) return outEquals.slice("--out=".length);

  const outIndex = args.indexOf("--out");
  if (outIndex >= 0) return args[outIndex + 1] ?? defaultOutFile;

  return defaultOutFile;
};
